### ISSUE TITLE
Set up a testflight on the official account of Open Food Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#101]
Set up a testflight on the official account of Open Food Facts

**Comment by snuff4** [comment]
I have read through the the procedure [Steps to put your app on TestFlight](https://medium.com/@dmathewwws/steps-to-put-your-app-on-testflight-and-then-the-ios-app-store-10a7996411b1) nicely explained. 
For immediate testing, we can do Internal testing upto 25 members. iTunesConnect needed

**Comment by teolemon** [comment]
Thanks @aleene

**Comment by aleene** [comment]
Still need to sort out how multiple Xcode users can help develop.

**Comment by teolemon** [comment]
I'm going to launch a call for help in iOS. But via GitHub, I suppose ?

**Comment by aleene** [comment]
If other developers make changes on Github, I could pull the changes and put them to the store.
