### ISSUE TITLE
Non i18n string

### ISSUE THREAD

**Issue by yarons** [openfoodfacts/openfoodfacts-ios#107]
https://github.com/openfoodfacts/openfoodfacts-ios/blob/f94ca834e3ceedca152b431e39764de12381bd4f/Sources/Models/ViewModel/PictureViewModel.swift#L20

This string assumes that the language is English or any other language, in an i18n world it's not working because languages tend to have different grammar and a word that may be added at the end of the sentence in English might just be in the middle of the sentence in Hebrew.

So unless we parameterize it or break it into cases, this code is bad practice in our case.

Thanks :smile:

**Comment by teolemon** [comment]
It seems to have changed slightly @yarons 
https://github.com/openfoodfacts/openfoodfacts-ios/blob/master/Sources/Models/ViewModel/PictureViewModel.swift

**Comment by aleene** [comment]
Is this still an issue? There are now three strings concatenated. Should be ok for any language?

**Comment by yarons** [comment]
@aleene Can you point me to those strings?

**Comment by aleene** [comment]
> @aleene Can you point me to those strings?

In the link by @teolemon above.

**Comment by yarons** [comment]
I haven't ran into the new string as part of the strings yet (I probably already translated these although I wasn't aware), do you prefer closing this one?

**Comment by aleene** [comment]
I'll close this one then, but keep the comments coming.
