### ISSUE TITLE
Product not found

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#109]
**Summary:** 
Scanned product not found on OFF. I know it is there (https://world.openfoodfacts.org/product/5900020029096/clusters-almonds-seeds-nestle)

**Steps to reproduce:** 
scan 5900020029096

**Expected behavior:** 
Show the scanned product.

**Observed behavior:** 
Asked me to add the product.

**Comment by keegho** [comment]
This code found by scanning but not by ordinary search.

6223000055939

**Comment by stephanegigandet** [comment]
This bug only happens on specific products? Does rescanning the same product sometimes work? I'm trying to guess if it's a network / timeout issue, or if it's caused by the values of the returned JSON data (if any JSON data is returned).

**Comment by aleene** [comment]
Indeed needs more testing.

**Comment by aleene** [comment]
The action for this is in class `ProductService`. And function `getProduct(byBarcode:isScanning:onSuccess:)`.
A test on a negative product reveals that the network interaction is a success, but the product is not found.

**Comment by aleene** [comment]
Think I found it, its interrogating the .net server.

**Comment by teolemon** [comment]
I'm closing this one. Perhaps we should remove all referennces to .net
