### ISSUE TITLE
Landscape scanning

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#113]
When scanning in landscape the orientation is not taken into account by the scanner. This means that left is up, up is right, etc.

**Comment by aleene** [comment]
When I turn to portrait and back to landscape, it works as it should. So this is an initialisation issue.

**Comment by stephanegigandet** [comment]
Can we just lock the app orientation in Portrait mode (like on the Android app). We don't want the app switching from portrait to landscape when we turn the phone to scan the barcode.

**Comment by aleene** [comment]
We can lock it, but why not support it? It is now working for 95%.

**Comment by stephanegigandet** [comment]
Mostly for scanning: many people hold the product in one hand, and with the other hand they hold the phone and they rotate the phone if the barcode is held vertically. But that doesn't work if the portrait mode is not locked: the barcode scanner line rotates as well and it's very hard to scan a vertical barcode, which can be quite frustrating.

**Comment by aleene** [comment]
That depends on the scanning library used. With FoodViewer the orientation of the barcode does not matter, nor the orientation of the device. As user you should not have to care about orientations.

**Comment by stephanegigandet** [comment]
In that case sure, my comment is valid only for the food scanners that display a red line to indicate how to scan.

**Comment by aleene** [comment]
The barcode scanner of the app scans barcodes in any orientation. I wonder even it even captures barcodes outside the view that I see.

**Comment by aleene** [comment]
I added a line to the initialiser of the video capture. It is working now.

It could do with some extra work though. The code I added is a stopgap: it works, but it is not how it should be done. Changing orientation could be smoother.
