### ISSUE TITLE
History not working

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#114]
My search history is not visible on the history page.

**Comment by aleene** [comment]
We have to figure out where the scan results are available and presented. At that moment one can save to the history as well. Probably this should happen in a background thread.

After successful scanning `ScannerViewController.handleGetProductSuccess(barcode:product:)` is called. This calls `ScannerViewController.showProduct(:)`, which launches the product viewcontroller.

**Comment by aleene** [comment]
Success!

**Comment by teolemon** [comment]
Is it fixed ? I think @philippeauriach also worked on some fix ?

**Comment by aleene** [comment]
Works now.
