### ISSUE TITLE
Support iOS 9

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#115]
**Summary:** 

The app does not support IOS 9 when building

**Observed behavior:** 
When building for IOS 9 (project and target!) we get an error message, that the module KingFisher requires at least IOS 10.

**Xcode version:** 
Xcode 10.1 and Swift 4 (needed for KIngFisher version 5)

**Screenshots:** 
![screen shot 2019-01-20 at 10 28 35](https://user-images.githubusercontent.com/1329905/51437501-7d5aef00-1c9f-11e9-9c4c-818169356df2.png)

**Comment by aleene** [comment]
I contacted the developer of KingFisher. https://github.com/onevcat/Kingfisher/issues/1093

**Comment by philippeauriach** [comment]
I did a quick tour of our libs, and KingFisher is not the only lib having iOS 10 min : 
- XLPagerTabStrip: 9.3
- KingFisher: 10.0
- NotificationBanner: 10.0
- FloatingPanel: 10.0
- IBLocalizable: 10.0

**Comment by aleene** [comment]
Will be a lot of work for a small market.

**Comment by teolemon** [comment]
@philippeauriach @aleene I believe we can call it quits on ios 9 ?

**Comment by clarissaj** [comment]
@teolemon should this issue be closed? I imagine supporting iOS 9 is no longer reasonable given iOS 16 just released last week!

**Comment by teolemon** [comment]
@clarissaj you're quite right 👍 closing
