### ISSUE TITLE
Change name from "Open Nutrition" to "OpenFoodFacts"

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#135]
Change name from "Open Nutrition" to "OpenFoodFacts"

**Comment by snuff4** [comment]
![screenshot 2019-02-11 at 7 42 06 pm](https://user-images.githubusercontent.com/30552772/52568586-2a570080-2e35-11e9-8406-a566731e040a.png)

It will crop the name, is it fine?

**Comment by aleene** [comment]
Probably this requires a new app on the app store.

**Comment by teolemon** [comment]
That's the name of the V1, so V2 won't change anything to that regard.
