### ISSUE TITLE
make the app iPad compatible

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#14]
make the app iPad compatible. currentll, I can only see it in iPhone mode.

**Comment by Tovkal** [comment]
For starters it can be made compatible so it sizes nicely, should be easy.

Custom UI should be made, so for instance search results and product detail are displayed using a master-detail interface

**Comment by teolemon** [comment]
the simple compatibility looks good enough for a 1st version.

**Comment by Tovkal** [comment]
Basic support enabled in ec339f8b30b29a882f211f7720cd9b0102f6feda. Will be in the next beta.

**Comment by teolemon** [comment]
Can we close this one ? Works fine for me.

**Comment by Tovkal** [comment]
Technically yes, but I would like this to be implemented in the future to better use the screen real estate:

![Master-detail example](https://i.imgur.com/uOSxxA2.png)

**Comment by SahilDhawan** [comment]
The current application can be made compatible with iPads by using Auto Layout. Auto Layout helps to provide different constraints for different layouts and using that we can add compatibility for iPads.

**Comment by tusharjindal353** [comment]
This can be easily done by using the split view controller.I have done this several time.I can do this for you if you assign this task to me

**Comment by baquer** [comment]
I can easily do this task , if you assign this to me .

**Comment by teolemon** [comment]
Closing since it was deployed. Agreing with @Tovkal that we can do better.
