### ISSUE TITLE
Add link to the Nova methodology in the ingredients tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#141]
Add link to the Nova methodology in the Ingredient tab
https://world.openfoodfacts.org/nova
The url should be translatable, and the button should say: Learn more (it can be an information icon)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/68286368-45336a00-0081-11ea-8ef6-9bad043dbe6a.png)

**Comment by aleene** [comment]
This implies an extra row for nova.
