### ISSUE TITLE
When there's no result in search, propose adding products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#145]
When there's no result in search, propose adding products. 
Currently we only have: "No results".
We could have: "We don't have any matching products. Try rephrasing your search or scan the barcode of the product to start adding it to Open Food Facts"
Display a "Scan product" button in the view below

**Comment by aleene** [comment]
We can start with adding the other text?

**Comment by teolemon** [comment]
We can perhaps close this one.
