### ISSUE TITLE
Clean the login/signup page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#184]
![image](https://user-images.githubusercontent.com/1689815/53516441-9f306880-3acc-11e9-85ad-bb3cf06e0018.png)

**Comment by aleene** [comment]
![IMG_1063](https://user-images.githubusercontent.com/1329905/69451694-48587680-0d60-11ea-958c-296cb8f06aa6.jpeg)

**Comment by teolemon** [comment]
Looks good to me. I would very much in favor of adding buttons but it's better already.

**Comment by aleene** [comment]
These ARE button, IOS style.
