### ISSUE TITLE
String bug in settings

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#185]
![image](https://user-images.githubusercontent.com/1689815/53516588-f33b4d00-3acc-11e9-897d-f5caff66e685.png)

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-ios/blob/master/Sources/en.lproj/Localizable.strings
The strings seems to be there.

**Comment by snuff4** [comment]
Can you reproduce this bug, on the latest branch? I am not able to find any issue in the code that will reproduce this.

**Comment by snuff4** [comment]
Ah, found it. In the localizable strings, "settings.information.discover" has been replaced by "settings.sections.discover"
