### ISSUE TITLE
Product loaded in French when the UX is in Dutch

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#203]
![image](https://user-images.githubusercontent.com/1689815/53635139-7c14ce80-3c1c-11e9-87e7-e1f007b1f7e6.png)
The ingredient list is in French, while a Dutch ingredient list exists

This is a regression from V1. This is also SUPER important for Belgium and Switzerland.

Product: https://be.openfoodfacts.org/product/5400113561767/aardappelpuree-delhaize
Barcode to scan: https://barcode.tec-it.com/en/EAN13?data=5400113561767

**Comment by aleene** [comment]
![screen shot 2019-03-02 at 16 07 58](https://user-images.githubusercontent.com/1329905/53683815-7e068c80-3d05-11e9-9e29-78e58587bc1c.png)

When running from Xcode I get a crash when I try to type in this barcode.

**Comment by teolemon** [comment]
weird. Latest Testflight works for me (just tested again a couple of seconds ago).

**Comment by aleene** [comment]
The version from Testflight works. It seems the app does not take into account any device language settings.

**Comment by teolemon** [comment]
Here are the currently multilingual fields that I know of. We don't display them all on the iOS version
```
    <string-array name="fields_array" translatable="false">
        <item>product_name</item>
        <item>generic_name</item>
        <item>ingredients_text</item>
        <item>other_information</item>
        <item>conservation_conditions</item>
        <item>recycling_instructions_to_discard</item>
        <item>recycling_instructions_to_recycle</item>
        <item>warning</item>
        <item>customer_service</item>
        <item>image_front_url</item>
        <item>image_ingredients_url</item>
        <item>image_nutrition_url</item>
    </string-array>
```

**Comment by aleene** [comment]
I think the language specific fields are not decoded from the json, so they are not available.

**Comment by aleene** [comment]
How can I push my local changes to a specific branch/fork within xcode. When I try to commit there is not the option of my local branch (as I started on the master, I guess).

**Comment by teolemon** [comment]
I would clone the repo somewhere else on the disk, do a git branch on this clone, and copy paste your work on that clone, and then commit the new branch ?

**Comment by aleene** [comment]
I already work in my local clone, I guess I do not know how to branch.

**Comment by aleene** [comment]
So I found where I can create a new branch. Not sure if I pushed all required changes. Code can be cleaned up.

**Comment by aleene** [comment]
Now where does the image stuff happen?

**Comment by teolemon** [comment]
Ok, solved by @aleene 
The image part remains to be done.

**Comment by aleene** [comment]
The image part needs to be merged you mean.

**Comment by teolemon** [comment]
yup, sorry. Can you create a PR with your branch @aleene ?

**Comment by aleene** [comment]
I guess this one is solved. I get the dutch image when working with an iPad set in dutch.
