### ISSUE TITLE
Remove the ":" in the allergen alert message

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#204]
![image](https://user-images.githubusercontent.com/1689815/53635369-2e4c9600-3c1d-11e9-8344-3c2110472a70.png)
This is ugly

**Comment by snuff4** [comment]
That colon is actually for the Label, so I came up with this - 

![img_81491f3694fa-1](https://user-images.githubusercontent.com/30552772/53681351-67186800-3d0e-11e9-91c8-59c6c6ccdcc1.jpeg)
