### ISSUE TITLE
Many string names across the app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#207]
I'm not familiar with iOS translation mechanisms. Why does this keep happening ? 
I saw one in French settings, now in the Dutch product page.
![image](https://user-images.githubusercontent.com/1689815/53635638-09a4ee00-3c1e-11e9-99c0-ab225da0d0c4.png)

**Comment by aleene** [comment]
If the translation file is incomplete, it puts the default string.

**Comment by teolemon** [comment]
Can we default to English ?

**Comment by snuff4** [comment]
Should be solved through #232 , #230 
Can you test this again? @teolemon

**Comment by teolemon** [comment]
Closing. Will reopen if I encounter the issue again.
