### ISSUE TITLE
Inconsistent nutrition table behaviour

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#208]
![image](https://user-images.githubusercontent.com/1689815/53636084-50471800-3c1f-11e9-86c1-6a6639a0ca6d.png)
![image](https://user-images.githubusercontent.com/1689815/53636093-550bcc00-3c1f-11e9-9571-5f64dc6b9c3f.png)
![image](https://user-images.githubusercontent.com/1689815/53636101-5b01ad00-3c1f-11e9-9353-1bc4a555de64.png)

Unconsistent nutrition table behaviour. Any idea what's going on ?

**Comment by teolemon** [comment]
Ok, we're going to stream the nutrition table using HTML generated by the server to temporally solve this one and many others.

**Comment by aleene** [comment]
So close this one?

**Comment by teolemon** [comment]
yes. It's much easier this way.
