### ISSUE TITLE
Inconsistent Country field behaviour

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#209]
![image](https://user-images.githubusercontent.com/1689815/53636213-ae73fb00-3c1f-11e9-8560-a05963cf9988.png)
![image](https://user-images.githubusercontent.com/1689815/53636221-b92e9000-3c1f-11e9-84bc-ef70ef6dbc32.png)

**Comment by aleene** [comment]
Non existing product?

**Comment by teolemon** [comment]
it's probably a server side issue
