### ISSUE TITLE
Baby milks nutrition tables off by a magnitude + rounding error

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#213]
Baby milks nutrition tables off by a magnitude + rounding error

![image](https://user-images.githubusercontent.com/1689815/53641828-70330780-3c30-11e9-8687-16de79657d05.png)

**Comment by teolemon** [comment]
Ok, we're going to stream the nutrition table using HTML generated by the server to temporally solve this one and many others.

**Comment by philippeauriach** [comment]
Working on it right now
