### ISSUE TITLE
Modifiers like >  < and ~ are not visible on mobile 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#217]
![image](https://user-images.githubusercontent.com/1689815/53644899-00c11600-3c38-11e9-9aff-a0fe26f8f6cd.png)
Modifiers like >  < and ~ are not visible on mobile 
(in addition to the rounding/magnitude issues)
Search for "Pot au Feu Golden Virginia"

**Comment by aleene** [comment]
Need an example barcode for testing

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/product/3288111212100/milumel-croissance-maxi-format-lactel
https://barcode.tec-it.com/en/EAN13?data=3288111212100

**Comment by teolemon** [comment]
But we pretty much solved this one using the HTML include.
I would not invest time and effort into trying to bring the native table back right now.
