### ISSUE TITLE
Add User-Agent header to API requests when an user scans a product

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#220]
Ensure we send back a Header on scan queries to the API (and only scan)
For Android, we send back:
"Open Food Facts for Android - version 2.9.7 - Scan"
"Open Food Facts for Android - version 2.9.7 - Product Browsing"

**Comment by stephanegigandet** [comment]
This would be very useful in order to compute better scan statistics and product popularity.

**Comment by aleene** [comment]
Any info what an agent header is?

**Comment by aleene** [comment]
https://stackoverflow.com/questions/26219997/how-can-i-set-the-user-agent-header-of-a-uiwebview-in-swift
