### ISSUE TITLE
Clicking on upload when the list is empty blocks the app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#226]
Clicking on upload when the products to be uploaded list is empty blocks the app
![image](https://user-images.githubusercontent.com/1689815/53732088-1410f300-3e7d-11e9-90ba-4cfde1ad204f.png)

**Comment by SuzGupta** [comment]
I think this is because the list is empty. Still present in v3.1 build 25.

**Comment by aleene** [comment]
Will add a check on number of upload items.

**Comment by aleene** [comment]
Sort of the same issue as #466.

**Comment by aleene** [comment]
The button will be disabled, when there are no upload items.
