### ISSUE TITLE
Provide a fallback to English for all strings

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#227]
![image](https://user-images.githubusercontent.com/1689815/53732156-4a4e7280-3e7d-11e9-9803-cbeca7354e12.png)
![image](https://user-images.githubusercontent.com/1689815/53732165-54707100-3e7d-11e9-8111-8a0f461ce2da.png)
![image](https://user-images.githubusercontent.com/1689815/53732171-59cdbb80-3e7d-11e9-87f4-9c3ed90e1f04.png)
![image](https://user-images.githubusercontent.com/1689815/53732175-5df9d900-3e7d-11e9-86ea-186cc88fdfa1.png)
![image](https://user-images.githubusercontent.com/1689815/53732185-66521400-3e7d-11e9-8d89-391f2383f0c2.png)

**Comment by aleene** [comment]
It is the approach of translations used in the app. Normally the key is the right (english) translation, but here encoded keys have been used. Not sure if that is easy to change.

**Comment by snuff4** [comment]
This is bad. I am working on this issue. 
![simulator screen shot - iphone 7 - 2019-03-04 at 18 50 41](https://user-images.githubusercontent.com/30552772/53735970-7a623980-3eae-11e9-976e-c88e01fc2299.png)

**Comment by snuff4** [comment]
"user.alert.logout-confirmation.title" = "Confirm Logout";
"user.alert.logout-confirmation.subtitle" = "Are you sure you want to log out ?"; 

These two in the localisable strings, but cannot find them in the languages in Xcode; that's why the keys is being shown. @teolemon @aleene any help?

**Comment by snuff4** [comment]
@teolemon  works ! 💯 
![simulator screen shot - iphone x - 2019-03-04 at 20 35 16](https://user-images.githubusercontent.com/30552772/53741753-12ffb600-3ebd-11e9-8686-1b38cd0a4392.png)

**Comment by aleene** [comment]
I think that most localization happens in the string extension, where var localized is defined. Maybe it is possible to intercept empty strings here and replace them with english ones.

**Comment by snuff4** [comment]
@aleene Actually the location where the localized strings were updated was different from where Xcode was taking. 

Now @teolemon has updated the location, and all the issues related to the keys being shown instead of the string should be solved! 👍

**Comment by aleene** [comment]
Ah the xliff issue

**Comment by teolemon** [comment]
Ok, so I updated the Crowdin config. This bug should thus be less important, since the localizable files are now updated and in the right place @aleene @snuff4 .
We can also kill the xliff files with a PR.

**Comment by teolemon** [comment]
Removing it as a release-blocker as a result.

**Comment by aleene** [comment]
Seems solved to me.
