### ISSUE TITLE
Environment impact doesn't work because we don't explicitely ask for it

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#229]
Environment impact doesn't work because we don't explicitely ask for it.
Change made by @aleene during the multilingual fix.
cc @stephanegigandet

**Comment by philippeauriach** [comment]
@aleene I dont get the following comments : disabled to get all fields, not only those specified
         // we cannot use the summary or the list as the tags are product and language dependent.

**Comment by aleene** [comment]
In the old situation all required fields for the json where listed. Unfortunately this will leave out the fields that are language specific. This is for each product different. For instance a a json could have keys like `product_name_en`, `product_name_th`, `product_name_zh`, etc. The same for the generic name and ingredients.

**Comment by teolemon** [comment]
I think we do an after the fact query on Android with the extra stuff we need.
I can also have @stephanegigandet tweak the server behaviour to return environment fields by default.

**Comment by aleene** [comment]
Two things: add the environment stuff by default. And redesign the multilingual json, so that keys are not product dependent.

**Comment by teolemon** [comment]
thnaks @aleene
