### ISSUE TITLE
NOVA disappears in online mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#273]
https://barcode.tec-it.com/en/EAN13?data=3560071018085
![image](https://user-images.githubusercontent.com/1689815/54125349-07ecde80-4405-11e9-992d-c6b5ff330e6f.png)
![image](https://user-images.githubusercontent.com/1689815/54125351-0d4a2900-4405-11e9-958d-5f053296a861.png)
https://fr.openfoodfacts.org/produit/3560071018085/pois-chiches-au-sel-de-noirmoutier-carrefour-bio
https://world.openfoodfacts.org/api/v0/product/3560071018085.json (It's there)

**Comment by stephanegigandet** [comment]
The NOVA field is in https://fr.openfoodfacts.org/api/v0/produit/3560071018085/pois-chiches-au-sel-de-noirmoutier-carrefour-bio
Which field is the app requesting / accessing to display NOVA?

**Comment by philippeauriach** [comment]
The nova_group field is an int in the json returned here, today the app parse this field as a string (returned as a string on some products, as an int on some others).

**Comment by philippeauriach** [comment]
Fixed in #190

**Comment by aleene** [comment]
There are issues with the api. Some fields changed from sending int to string or vice-versa.
