### ISSUE TITLE
Make the Nutri-Score larger on the summary tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#276]
Make the Nutri-Score larger on the summary tab

**Comment by snuff4** [comment]
Is this fine @teolemon ?

Before / After
![Screenshot 2019-03-15 at 9 42 13 PM](https://user-images.githubusercontent.com/30552772/54447433-6bfa0480-476f-11e9-99fb-02c4a9857fe0.png)
