### ISSUE TITLE
Add a title for the Nutrient levels

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#287]
Add a title for the Nutrient levels.

"Nutrient levels per 100 g/100mL"
This needs to be fixed on the summary and nutrition tabs.

**Comment by teolemon** [comment]
@aleene can you take care of this one ?

**Comment by aleene** [comment]
What do you think of? The table is still a web version? So there is already a title. Below the photo there is a text "per portion". Why is that there?

**Comment by teolemon** [comment]
it's not the nutrition table, but the circular color codes and nutrient level: "1,2 G, Salt in high quantity"
They need to have "Nutrient levels per 100 g" on top

**Comment by aleene** [comment]
So this can be closed?

**Comment by teolemon** [comment]
merged. we can close
