### ISSUE TITLE
Typo in string "Login in with your account"

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#289]
`Login in with your account will associate all your contributions to your account.`
>>
`Logging in with your account will associate all your future contributions to it.`

**Comment by aubincleme** [comment]
@teolemon Looks like the string you mentioned (`Login in with your account will associate all your contributions to your account.`) is not the current default in the english version of the app. The current default seems to be `Logging in with your account will give you credit for all your contributions to food transparency.`(FTR the translation key is `user.why-log-in.text`).

With that in mind, is the issue still relevant? We can update the other locales of the app to be aligned with the current english version, or move everything to the new translation string that you provide.

**Comment by teolemon** [comment]
The current English string is fine. Correcting the target strings still in English would be nice.

https://github.com/openfoodfacts/openfoodfacts-ios/search?q=Login+in+with+your+account+will+associate+all+your+contributions+to+your+account&unscoped_q=Login+in+with+your+account+will+associate+all+your+contributions+to+your+account

**Comment by philippeauriach** [comment]
Sorry @teolemon , just to be sure, I don't think "Logging" is the word you want here : https://www.linguee.fr/anglais-francais/traduction/logging.html

**Comment by teolemon** [comment]
Indeed the wording is shitty.
`To get credit for your contributions to Open Food Facts, make sure to log in with your contributor account` ? @philippeauriach @aubincleme

**Comment by philippeauriach** [comment]
> Indeed the wording is shitty.
> `To get credit for your contributions to Open Food Facts, make sure to log in with your contributor account` ?

Good for me

**Comment by aubincleme** [comment]
Looks nice :)

**Comment by aubincleme** [comment]
@teolemon should be fine now
