### ISSUE TITLE
The travis build is broken and should be fixed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#290]
/Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'carthage bootstrap --platform iOS --cache-builds' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)

**Comment by aleene** [comment]
You mean the Travis-build?

**Comment by aleene** [comment]
Same as #395

**Comment by teolemon** [comment]
seems to be working now. closing
