### ISSUE TITLE
Wrong placement for nutrient levels under the Nutri-Score

### ISSUE THREAD

**Issue by Antoinebourcy** [openfoodfacts/openfoodfacts-ios#301]
Weird thing : In "Nutrition", on IOS version, under the Nutri-Score it's written "the nutrients levels per serving" But the nutrients value for the Nutri-Score are equal for 100gr. (Fat/Saturated Fat/Sugar/Salt) 

**Expected behavior:** 

- See "Nutrients levels for 100gr" and not "Nutrients levels per serving"

**Device and iOS version:** 

Apple iPhone / running iOS : Unknown

**Screenshots:** 
No

**Comment by aleene** [comment]
This seems ok now
