### ISSUE TITLE
Problem with offline message in Dutch

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#308]
![image](https://user-images.githubusercontent.com/1689815/59936830-3db45100-9451-11e9-908f-9193bf4db8c1.png)

**Comment by teolemon** [comment]
Dutch, Belgium (nl_BE)            1.5
Dutch, Netherlands (nl_NL)        1.5

**Comment by teolemon** [comment]
![Capture d’écran 2019-06-21 à 18 26 24](https://user-images.githubusercontent.com/1689815/59937219-23c73e00-9452-11e9-9b72-46041904e9ed.png)

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-ios/blob/master/Sources/nl.lproj/Localizable.strings
https://github.com/openfoodfacts/openfoodfacts-ios/blob/master/Sources/Localization/nl.lproj/Localizable.strings

**Comment by teolemon** [comment]
The canonical Crowdin file is: 
``` 
https://github.com/openfoodfacts/openfoodfacts-ios/blob/master/Sources/Localization/nl.lproj/Localizable.strings
```

**Comment by aleene** [comment]
Which means the string is not listed in Localizable strings.

**Comment by teolemon** [comment]
I'm currently resyncing with 2 files for nl, instead of one.  Is your phone in nl or nl-be ?

**Comment by aleene** [comment]
nl-nl
The string does not seem available on Crowdin.

**Comment by aleene** [comment]
The strings are not available in localizable.strings. If I add them by hand everything is OK. I can push this change to master if you want.

**Comment by aleene** [comment]
It is only an issue the the dutch file. The others are OK.

By the way what is wrong with Mongo?

**Comment by teolemon** [comment]
I've updated some template on Crowdin, I'm curious to see if this fixes the bug.
Did I say a thing about Mongo ?

**Comment by aleene** [comment]
No I did. The localizable Mongo-strings are very strange

**Comment by aleene** [comment]
This can be closed?
