### ISSUE TITLE
Reload image placeholder on upload

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#31]
Reload image placeholder on upload of an image

**Comment by Tovkal** [comment]
So on a product's detail with the placeholder, if the user takes one picture it should be displayed even though it is not selected (so if the user searches later for the product the image will not appear)?

**Comment by teolemon** [comment]
I had a placeholder, and I uploaded an image. So I assume the server selected the image in that case ?
But if the image is not selected, it would be confusing to show it.
Or perhaps a drag to reload, to see if anything has changed ?

**Comment by Tovkal** [comment]
I don't think the server selects an image automatically.
