### ISSUE TITLE
Constraint issue warning

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#310]
![Screenshot 2019-06-22 at 18 11 27](https://user-images.githubusercontent.com/1329905/59966211-35bfe400-9519-11e9-9adc-a40ef6055265.png)

**Comment by teolemon** [comment]
@aleene is it something you think can be solved, or can we close it ?

**Comment by aleene** [comment]
This is the same as #678. I'll close this one.
