### ISSUE TITLE
realm-cocoa.framework - Incompatible Swift version (5.0 vs 4.2.1)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#313]
Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 4.2.1 (swiftlang-1000.11.42

**Comment by teolemon** [comment]
@aleene @philippeauriach https://github.com/Carthage/Carthage/issues/2632
This is merely a question to Carthage being too picky, apparently

**Comment by aleene** [comment]
Seems solved by now.
