### ISSUE TITLE
Manual Language switcher on product addition

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#32]
The server will automatically add the proper country on product addition, based on the IP address.
But It won't take the right language by default. If the iPhone is in English but the product in French, it will select the English language.
So it should be possible to select the main language of the product on product addition.

**Comment by Tovkal** [comment]
So add a drop down list when adding a product to select a language, right?

I don't see the API exposing a list of languages (would be nice), so I'll search one.
