### ISSUE TITLE
Add support for the new server-side Vegan/Vegetarian/Palm Oil detection

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#321]
Mockups:
![image](https://user-images.githubusercontent.com/1689815/67160231-f54d6700-f34e-11e9-92c1-471bc7ed0283.png)

Add support for the new server-side Vegan/Vegetarian/Palm Oil detection
- [ ] Update the various product queries to include the `ingredients_analysis_tags` field: `https://world.openfoodfacts.org/api/v0/product/3564700459447.json?fields=ingredients_analysis_tags`
{"status":1,"product":{"ingredients_analysis_tags":["en:palm-oil-free","en:non-vegan","en:non-vegetarian"]},"code":"3564700459447","status_verbose":"product found"}
- [ ] We're adding a Detection taxonomy to be able to add new detections on the fly and to reduce hardcoding/simplify implementation:
https://static.openfoodfacts.org/data/taxonomies/ingredients_analysis.json
It has: the tag, the name in various languages, the icon, the color.
- [ ] Explain why it is not vegan/vegetarian thanks to this field: `https://world.openfoodfacts.org/api/v0/product/3564700459447.json?fields=ingredients`

``` {"product":{"ingredients":[{"rank":1,"vegetarian":"no","vegan":"no","text":"Thon albacore","id":"en:yellowfin-tuna"},{"id":"en:water","text":"eau","vegan":"yes","vegetarian":"yes","rank":2},{"rank":3,"id":"en:salt","text":"sel","vegan":"yes","vegetarian":"yes"}]},"code":"3564700459447","status":1,"status_verbose":"product found"}``` 

- [ ] Add the following disclaimer `The analysis is based solely on the ingredients listed and does not take into account processing methods.`

**Comment by teolemon** [comment]
Web version example:
![image](https://user-images.githubusercontent.com/1689815/61800201-d3664600-ae2c-11e9-9943-2987cbc468c4.png)
![image](https://user-images.githubusercontent.com/1689815/61800219-d8c39080-ae2c-11e9-99b7-81a5fc822881.png)

**Comment by teolemon** [comment]
Here are the icons for the feature:
https://github.com/openfoodfacts/openfoodfacts-server/tree/master/icons

**Comment by teolemon** [comment]
Palm:
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/icons/monkey_happy.svg
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/icons/monkey_unhappy.svg
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/icons/monkey_uncertain.svg
Vegetarian:
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/icons/egg.svg
Vegan:
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/icons/leaf.svg

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/63027151-b31a2c00-beac-11e9-9a74-d940633e1704.png)
![image](https://user-images.githubusercontent.com/1689815/63027166-ba413a00-beac-11e9-9710-35e4d8840702.png)

**Comment by teolemon** [comment]
Here's a mockup we did for Android: 
![image](https://user-images.githubusercontent.com/1689815/64011966-0206c900-cb1d-11e9-924f-84f312d79027.png)

**Comment by teolemon** [comment]
Great @matotim 👍 Feel free to ping me here or on Slack if you need any help.
To simplify even further, and we're adding a taxonomy to be able to update everything on the fly:
https://static.openfoodfacts.org/data/taxonomies/ingredients_analysis.json

it should have: the tag, the name in various languages, the icon, the color

**Comment by teolemon** [comment]
@matotim are you on the Open Food Facts slack ? 
Here's the Android implementation, if it can make things easier:
https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2871/files

**Comment by matotim** [comment]
@teolemon yes I am ! Sorry for the delay, I didnt have much free time during the previous week.
Here's the current branch I'm working on : https://github.com/matotim/openfoodfacts-ios/tree/vegan-check

**Comment by teolemon** [comment]
I've created a PR so that it's easier to iterate.
https://github.com/openfoodfacts/openfoodfacts-ios/pull/414

**Comment by teolemon** [comment]
Also, for the icons and logic, we have taxonomies, so we can remove hardcoding and make the system future proof (to add other diets server-side)
Icons: https://ssl-api.openfoodfacts.org/files/app/ingredients-analysis.json
Icon path structure: "https://static.openfoodfacts.org/images/icons/" + icon + ".white.96x96.png";
Translations: https://static.openfoodfacts.org/data/taxonomies/ingredients_analysis.json

**Comment by teolemon** [comment]
We fixed a transient error with the JSON (the structure had changed because of an uncommited file) @matotim

**Comment by matotim** [comment]
I already said it on Slack #api, but there's a small error on https://ssl-api.openfoodfacts.org/files/app/ingredients-analysis.json -> the vegans and vegetarians icons are switched. Also, the vegetarian-unknown has the good icon (egg), but the vegan unknown also has the egg.

**Comment by teolemon** [comment]
it should have been fixed by @stephanegigandet @matotim

**Comment by matotim** [comment]
Feature is now implemented. I've not implemented the view in the scanner yet, but all the informations are available in the summary view.
For the icons, all the vegans icons are now 'leaf', but the vegetarian are also 'leaf' but should be 'egg'.

**Comment by teolemon** [comment]
Here are some complementary screenshots of the Android implementation 
![image](https://user-images.githubusercontent.com/1689815/72446808-84361800-37b4-11ea-8691-23487e6afe7a.png)
![image](https://user-images.githubusercontent.com/1689815/72446828-8c8e5300-37b4-11ea-83b4-a74bc4aa3fb6.png)
![image](https://user-images.githubusercontent.com/1689815/72446851-9748e800-37b4-11ea-9c9c-cb76769e9dd6.png)

**Comment by teolemon** [comment]
Reopening

**Comment by teolemon** [comment]
- The nag (when no ingredients are available) is not shown
- the app crashes on barcode 3267031040086

**Comment by teolemon** [comment]
Closing this one
