### ISSUE TITLE
Adding a new product always sends back "123456789" instead of the actual barcode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#325]
**Symptom:** Adding a new product always sends back "123456789" instead of the actual barcode
**Build:** Master version currently on TestFlight - Stable release works fine.
**Video:** https://twitter.com/TaciteData/status/1155089268722798592

**Comment by teolemon** [comment]
https://twitter.com/TaciteData/status/1155089268722798592

**Comment by aleene** [comment]
Is this only an interface issue or is the product not created?

**Comment by teolemon** [comment]
The one in the tweet doesn't seem to exist: 
5413226550528
http://world.openfoodfacts.org/product/5413226550528

Also the app crashes when you attempt to save it. So the product is not created I guess.

**Comment by aleene** [comment]
123456789 is part of the interface and seems to be unchanged after a new barcode has been scanned.

**Comment by aleene** [comment]
The issue lies here:
`    func getItemPendingUpload(forBarcode barcode: String) -> PendingUploadItem? {
        let realm = getRealm()
        let yyy = realm.object(ofType: RealmPendingUploadItem.self, forPrimaryKey: barcode)
        let xxx = yyy?.toPendingUploadItem()
        return xxx
`
The yyy is not created and stays nil. This is in an external library. I wonder if it is a timing issue.

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-ios/blob/18f3439ebc8e7c086394102728a1ce34777b16d2/Sources/Models/PersistenceManager.swift#L52

**Comment by teolemon** [comment]
@philippeauriach can you have a look ? was it working for you at the time ?

**Comment by aleene** [comment]
I think I solved this one, but I am swimming a bit in the dark here.

**Comment by philippeauriach** [comment]
Sorry, what is exactly the problem ? Just the UI showing "123456789" or the json sent to server having "123456789" ? Or both ? I'll check in depth tomorrow morning

**Comment by aleene** [comment]
In ProductAddViewController:
The app seems to try first a locally stored product and then a realm stored product
Both were nil however, and nothing happens
As there is a new barcode, there should be a local product,
but it is nowhere created
solution is to create productToEdit, when the barcode is set
and assign the barcode to productToEdit

**Comment by philippeauriach** [comment]
Added a suggestion in the commit above. I feel like changing too much in ProductAddController could introduce unwanted side effects, especially when updating an existing product. When creating it, it indeed does not exist so we should create one and pass it as `productToEdit`

**Comment by aleene** [comment]
Yes I was worried about side effects as well. I'll adopt your suggestion and delete the rest.

**Comment by philippeauriach** [comment]
Created. I also solved the problem making the AddProductVC appearing twice
