### ISSUE TITLE
PersistenceManager.swift:101:27: 'add(_:update:)' is deprecated

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#326]
![image](https://user-images.githubusercontent.com/1689815/62048462-4137b680-b20d-11e9-894b-97f61be336fc.png)

Showing All Issues
/openfoodfacts-ios/Sources/Models/PersistenceManager.swift:101:27: 'add(_:update:)' is deprecated: Pass .error, .modified or .all rather than a boolean. .error is equivalent to false and .all is equivalent to true.

**Comment by aleene** [comment]
Is solved in build 18
