### ISSUE TITLE
Change the Crashlytics id

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#336]
Change the Crashlytics id

**Comment by teolemon** [comment]
I'm pinging @Tovkal , it would be better to get access to the original account

**Comment by aleene** [comment]
It seems that we have to replace crashlytics with firebase. So let's remove it for the moment.

**Comment by aleene** [comment]
Note that the release version has had 25 crashes up to 16 oct 2019

**Comment by teolemon** [comment]
We're actually going to remove Crashlytics and move ahead with something open and privacy sensitive. cc @philippeauriach you might encounter traces of this.
