### ISSUE TITLE
Create a fastlane to upload dsyms to crashlytics

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#337]
Create a fastlane to upload dsyms to crashlytics

**Comment by mike011** [comment]
Doesn't this already exist in the `refresh_dsyms` lane?

**Comment by aleene** [comment]
Still relevant #336 ?

**Comment by teolemon** [comment]
We're moving ahead with some other solution that's more privacy compatible (self-hosted Sentry instance)

**Comment by teolemon** [comment]
cc @philippeauriach
