### ISSUE TITLE
Crash in didTapSaveNutrimentsButton()

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#339]
**Checklist**
- [x] Bug Report

**Summary:** 
In the bug reports a crash is reported in this action method.
![Screenshot 2019-08-31 at 19 17 44](https://user-images.githubusercontent.com/1329905/64067145-09fd6080-cc24-11e9-865e-92b6104be623.png)
I find the crash log not very interesting.

**Steps to reproduce:** 

Please provide detailed steps for reproducing the issue.

 - 
 -  
 -  

**Expected behavior:** 

What did you expect the app to do?

**Observed behavior:** 

What did you see instead?  Describe your issue in detail here.

**Device and iOS version:** 

Apple iPhone X running iOS 13.0

**Screenshots:**

**Comment by aleene** [comment]
Does work for me, so need info to recreate this crash.

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/66208653-e8294a80-e6b5-11e9-8f4d-2a0224f9fd32.png)
Bug in version 3.1 from TestFlight on iPhone X in iOS 13 beta:
As soon as I press “save” the app crashes
Image from iOS
