### ISSUE TITLE
Offline mode for contribution

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#34]
If no connexion is detected:
- store the added images for later, and add a button to retry uploading them
- assume the product doesn't exist, show the new product form, let the user add names and photos, and store in a "Offline" list that the user can upload when he's back online. If the barcode exist, check the name/brand/quantity do not exist, and upload images without selecting them

**Comment by aleene** [comment]
Is related to a bulk upload mode.

**Comment by teolemon** [comment]
- If you rescan the product a second time after adding photos, it should display the product page, and offer to upload the photos if online.
- There should be a view with a list of pending products.
- There should be a slight prompt to upload the product (either a count badge on the offline icon, or a notification, or it should happen automatically if that kind of things is possible on iOS)

**Comment by teolemon** [comment]
That looks mostly fixed to me. Closing. Thanks @Tovkal 👍
