### ISSUE TITLE
Main language change

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#340]
![Screenshot 2019-09-08 at 10 04 40](https://user-images.githubusercontent.com/1329905/64485392-93aebe80-d220-11e9-962e-85d62e7a3fc1.png)

**Comment by aleene** [comment]
There is no crash log for this crash.

**Comment by aleene** [comment]
I was not able to repeat this crash.

**Comment by teolemon** [comment]
It's an iPhone XS on the latest testflight.

**Comment by aleene** [comment]
Seems to be solved for IOS 13.

**Comment by aleene** [comment]
On to the next bug #357
