### ISSUE TITLE
Not able to edit

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#341]
**Summary:** 
Having switched back to the Appstore version (the Testflight one crashed whenever I wanted to edit):

Whenever I want to edit an already existing product, I scan the product and want to edit, but then I get forwarded to the off page and see “this page does not exist”
![image](https://user-images.githubusercontent.com/1329905/64541082-92b18600-d321-11e9-840b-53c455a7a9b4.png)

**Steps to reproduce:** 
could you copy paste the url that the app try to display please ? (using the share button at the bottom of your screenshot): https://world.openfoodfacts.org/type=edit&code=4006229028258
**Device and iOS version:** 
This is the stable apple store version

**Comment by aleene** [comment]
> iOS 13.1 beta on an iPhone X. Whenever editing anything and clicking on “Save”. Doesn’t matter the product, doesn’t matter what I had edited

**Comment by stephanegigandet** [comment]
There seems to be a 301 redirect that is broken:

 - - [08/Oct/2019:09:14:22 +0200] "GET /api/v0/product/36800151246.json?fields=brands,code,environment_impact_level_tags,image_front_url,image_front_small_url,image_small_url,image_url,nova_group,nutrition_grades,product_name,quantity,states HTTP/2.0" 200 671 "-" "OpenFoodFacts/3.0 (org.openfoodfacts.scanner; build:11; iOS 13.1.0) Alamofire/4.8.1"
 - - [08/Oct/2019:09:14:22 +0200] "GET /api/v0/product/36800151246.json?fields=additives_tags,allergens,allergens_hierarchy,allergens_tags,amino_acids_tags,brands,brands_tags,categories_tags,cities_tags,code,conservation_conditions,countries,countries_tags,created_t,creator,customer_service,editors_tags,emb_codes_tags,environment_impact_level_tags,environment_infocard,generic_name,image_front_url,image_ingredients_url,image_nutrition_url,image_small_url,image_url,ingredients_from_palm_oil_n,ingredients_from_palm_oil_tags,ingredients_from_or_that_may_be_from_palm_oil_n,ingredients_text,ingredients_that_may_be_from_palm_oil_tags,labels_hierarchy,labels_tags,lang,languages_codes,last_modified_by,last_modified_t,link,manufacturing_places,minerals_tags,no_nutrition_data,nova_group,nova_groups,nucleotides_tags,nutrient_levels,nutriments,nutrition_data_per,nutrition_grade_fr,nutrition_grades,origins,other_information,other_nutritional_substances_tags,packaging,product_name,purchase_places,recycling_instructions_to_discard,recycling_instructions_to_recycle,quantity,selected_images,serving_size,states,states_tags,stores,traces,traces_tags,url,vitamins_tags,warning,nutrition_table_html&lc=en,DE HTTP/2.0" 200 2657 "-" "OpenFoodFacts/3.0 (org.openfoodfacts.scanner; build:11; iOS 13.1.0) Alamofire/4.8.1"
 - - [08/Oct/2019:09:14:30 +0200] "GET /cgi/product.pl?type=edit&code=36800151246 HTTP/2.0" 301 34891 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1"
 - - [08/Oct/2019:09:14:30 +0200] "GET /type=edit&code=36800151246 HTTP/2.0" 404 9640 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1"
 - - [08/Oct/2019:09:15:06 +0200] "GET /api/v0/product/36800151246.json?fields=brands,code,environment_impact_level_tags,image_front_url,image_front_small_url,image_small_url,image_url,nova_group,nutrition_grades,product_name,quantity,states HTTP/2.0" 200 676 "-" "OpenFoodFacts/3.0 (org.openfoodfacts.scanner; build:11; iOS 13.1.0) Alamofire/4.8.1"
 - - [08/Oct/2019:09:15:06 +0200] "GET /api/v0/product/36800151246.json?fields=additives_tags,allergens,allergens_hierarchy,allergens_tags,amino_acids_tags,brands,brands_tags,categories_tags,cities_tags,code,conservation_conditions,countries,countries_tags,created_t,creator,customer_service,editors_tags,emb_codes_tags,environment_impact_level_tags,environment_infocard,generic_name,image_front_url,image_ingredients_url,image_nutrition_url,image_small_url,image_url,ingredients_from_palm_oil_n,ingredients_from_palm_oil_tags,ingredients_from_or_that_may_be_from_palm_oil_n,ingredients_text,ingredients_that_may_be_from_palm_oil_tags,labels_hierarchy,labels_tags,lang,languages_codes,last_modified_by,last_modified_t,link,manufacturing_places,minerals_tags,no_nutrition_data,nova_group,nova_groups,nucleotides_tags,nutrient_levels,nutriments,nutrition_data_per,nutrition_grade_fr,nutrition_grades,origins,other_information,other_nutritional_substances_tags,packaging,product_name,purchase_places,recycling_instructions_to_discard,recycling_instructions_to_recycle,quantity,selected_images,serving_size,states,states_tags,stores,traces,traces_tags,url,vitamins_tags,warning,nutrition_table_html&lc=en,DE HTTP/2.0" 200 2636 "-" "OpenFoodFacts/3.0 (org.openfoodfacts.scanner; build:11; iOS 13.1.0) Alamofire/4.8.1"
 - - [08/Oct/2019:09:15:11 +0200] "GET /cgi/product.pl?type=edit&code=36800151246 HTTP/2.0" 301 34889 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1"
 - - [08/Oct/2019:09:15:11 +0200] "GET /type=edit&code=36800151246 HTTP/2.0" 404 9641 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1"
 - - [08/Oct/2019:09:15:33 +0200] "GET /type=edit&code=36800151246 HTTP/2.0" 404 9655 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-ios/blob/f7c2eb7e66c1d39bef0dd2ae7165369c5bdc61c5/Sources/Helpers/URLs.swift#L19

**Comment by teolemon** [comment]
It has been fixed, but not released. 
The native edit mode should replace it, but the release is stuck on bugs:
#343, #340, #339

**Comment by aleene** [comment]
seems solved with build 18
