### ISSUE TITLE
APP crash on IOS 13 startup ('Access to UISearchBar's _searchField ivar is prohibited. This is an application bug')

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#343]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker.](https://github.com/openfoodfacts/openfoodfacts-ios/issues)

**Summary:** 
On the xcode console:
2019-10-04 19:37:23.355538+0200 OpenFoodFacts[878:130849] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Access to UISearchBar's _searchField ivar is prohibited. This is an application bug'

**Steps to reproduce:** 
build and run on Xcode 11.

**Expected behavior:** 
App did not run at all.

**Observed behavior:** 
crash

**Device and iOS version:** 
Xcode 13.1 on iPad

**Comment by philippeauriach** [comment]
Is this a bug in the prod app or only when building with Xcode 11 ? I am on 13.1.2 and no problem with the AppStore version.

**Comment by aleene** [comment]
Only building with xcode 11.
