### ISSUE TITLE
Xcode 11 (Notification Banner

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#347]
**Summary:** 
On starting the app in xcode 11 on a device.
```
dyld: Library not loaded: @rpath/MarqueeLabel.framework/MarqueeLabel
  Referenced from: /private/var/containers/Bundle/Application/31558BF8-36F1-40D7-B58D-4FB30BC628B8/OpenFoodFacts.app/Frameworks/NotificationBanner.framework/NotificationBanner
  Reason: image not found
```
**Steps to reproduce:** 
XCode 11 to use

**Comment by aleene** [comment]
From the NotificationBanner github:
```
To use NotificationBanner via Carthage simply add this line to your Cartfile:

Swift 5

github "Daltron/NotificationBanner" "master"
Then add NotificationBanner.framework and the dependencies SnapKit.framework and MarqueeLabel.framework in your project.
```
The current Cartfile is slight different and MarqueLabelSwift is added.

**Comment by aleene** [comment]
It seems MarqueeLabel is not ready for Xcode 11.

https://github.com/cbpowell/MarqueeLabel/issues/239

**Comment by SuzGupta** [comment]
@aleene I think the MarqueeLabel issue you referenced above is just saying that they removed the Swift Package Manager version of their framework because that was causing problems with Carthage. Since OFF doesn't use SPM, I don't think this affects the OFF project.

**Comment by aleene** [comment]
#350 solves this issue.
