### ISSUE TITLE
Offline mode for consultation

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#35]
- Download from the server, and store a reduced version (60MB) of Open Food Facts on the device.
- Read from this version when offline, go back to the API when online
- Offer to refresh the database in the settings
- Offer to refresh automatically when on wifi

**Comment by teolemon** [comment]
Blocked on the definition of a common standard for Android and iOS. A test version of the base has already been made.

**Comment by aleene** [comment]
Is it possible to get the database for specific countries? What does reuced mean?

**Comment by teolemon** [comment]
```
wget "https://world.openfoodfacts.org/data/en.openfoodfacts.org.products.csv"
```
```
#!/usr/bin/env python
from __future__ import absolute_import, division, print_function
import csv
from itertools import imap
from operator import itemgetter


def main():
    #delimiter = '	'
    #with open('en.openfoodfacts.org.products.csv', 'rU') as input_file:
        #reader = csv.reader(input_file, dialect=csv.excel_tab)
        #filebu = open(input_file, 'rU')
        #reader = csv.reader(input_file, dialect=csv.excel_tab)
        #with open('output.csv', 'wb') as output_file:
            #writer = csv.writer(output_file, delimiter=delimiter)
    import pandas
    df = pandas.read_csv('en.openfoodfacts.org.products.csv', sep='\t', low_memory=False)
    colnames = ['code','product_name', 'generic_name', 'quantity', 'brands', 'ingredients_text', 'allergens', 'traces', 'nutrition_grade_fr']
   #data = pandas.read_csv('en.openfoodfacts.org.products.csv', sep='\t', low_memory=False, names=colnames)
    #data.to_csv('output-small.csv', sep='\t', encoding='utf-8')
    df.to_csv('output-small.csv', columns = colnames)

            #, 34, 53
if __name__ == '__main__':
    main()

```

**Comment by teolemon** [comment]
output-small= 78,3 Mo for the whole world. Might have increased since 24.05.2017

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/data/output-small.csv
Database at 1GO, new export: 87MB

**Comment by aleene** [comment]
Very nice. Wonder how I can use this to enhance the app.

**Comment by teolemon** [comment]
Zipped, it goes down to 20MB for download.
If no connection is detected, fill the fields with an icon Not available offline and fill the values when you have them ?

**Comment by devjdg** [comment]
Mind if i ask, should we consider downloading products by category / certain specifics (parameters) or should it really be downloaded as a whole compressed data when there is no internet connection?

**Comment by teolemon** [comment]
Please note that some of the info above is obsolete. We have new files.

**Comment by teolemon** [comment]
I've created a special excerpt of the database, which has the required data to scan products for France. This is 11 Mb zipped, and 37Mb unzipped.
http://fr.openfoodfacts.org/data/offline/fr.openfoodfacts.org.products.small.csv.tgz

**Comment by teolemon** [comment]
http://fr.openfoodfacts.org/data/offline/fr.openfoodfacts.org.products.small.zip
http://fr.openfoodfacts.org/data/offline/large.zip (with all products, with all fields)

**Comment by teolemon** [comment]
I have fixed the CSV export for NOVA which wasn't exported correctly:
https://world.openfoodfacts.org/data/offline/en.openfoodfacts.org.products.small.csv.zip
