### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#355]
**Summary:** 

> it installs ok, but it crashes even before splash

**Steps to reproduce:** 
Run with an IOS below 13

**Device and iOS version:** 

IOS 13

**Screenshots:**

**Comment by aleene** [comment]
Probably happens in
```
        let searchField = searchController.searchBar.searchTextField
        searchField.isAccessibilityElement = true
        searchField.accessibilityIdentifier = AccessibilityIdentifiers.productSearchBar
```
The searchTextField is not available under IOS 12. In the crash log we have the error `[UIResponder doesNotRecognizeSelector:]`.

**Comment by SuzGupta** [comment]
Yeah, I was thinking that might be it.

**Comment by aleene** [comment]
@teolemon build 18 solved this issue?

**Comment by teolemon** [comment]
yes it did 👍
