### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#362]
**Summary:** 
IOS 13 has a dark mode. The app should support it. We have to go over all interface parts to see whether it complies.

**Comment by aleene** [comment]
There are white backgrounds that must convert to black.

**Comment by SuzGupta** [comment]
so, we'll want to make anything that lays atop a background transparent

**Comment by aleene** [comment]
And maybe set some backgrounds to .systemBackground

**Comment by aleene** [comment]
Also many UI elements might need to be set to the right system color.

**Comment by aleene** [comment]
This needs quite a few changes:
- all UI elements set to default (to start with)
- images require a dark mode variant (in white or gray?)

**Comment by teolemon** [comment]
![credits](https://user-images.githubusercontent.com/1689815/66703527-e98cef80-ed13-11e9-80f3-012b84aa25a8.jpg)
![history](https://user-images.githubusercontent.com/1689815/66703528-e98cef80-ed13-11e9-8525-f62150298185.jpg)
![product](https://user-images.githubusercontent.com/1689815/66703529-e98cef80-ed13-11e9-9ebd-aa1926262f83.jpg)
![search](https://user-images.githubusercontent.com/1689815/66703530-e98cef80-ed13-11e9-943c-38384fb104f1.jpg)
![settings](https://user-images.githubusercontent.com/1689815/66703531-ea258600-ed13-11e9-9b06-3a353f976495.jpg)
![settings1](https://user-images.githubusercontent.com/1689815/66703532-ea258600-ed13-11e9-916c-e4918a58d338.jpg)

**Comment by aleene** [comment]
What do you want to show?

**Comment by aleene** [comment]
Need to adapt NutriScore and Nova icons.

**Comment by teolemon** [comment]
![ingredients](https://user-images.githubusercontent.com/1689815/66704398-edbd0b00-ed1b-11e9-98d8-08b51ad459df.jpg)
![nutrition](https://user-images.githubusercontent.com/1689815/66704399-edbd0b00-ed1b-11e9-9f8b-b86c2ee53a22.jpg)
![home](https://user-images.githubusercontent.com/1689815/66704406-fad9fa00-ed1b-11e9-8b03-d0b3ad2d3550.jpg)
