### ISSUE TITLE
Check the API call doesn't have a //

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#369]
Double check the API call doesn't have a //
I saw some issues in the server logs.
https://github.com/openfoodfacts/openfoodfacts-ios/pull/257/files#diff-63c0ecf709036ade776946b575da3d5cR18

**Comment by aleene** [comment]
Those are errors from just now?

**Comment by aleene** [comment]
Was indeed a / to many.
