### ISSUE TITLE
Crash on photo taking

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#371]
![image](https://user-images.githubusercontent.com/1689815/66743254-cb410400-ee79-11e9-816f-d918dbc7c6c3.png)
``` Un nouveau produit, j’ai appuyé sur “front picture”, j’ai visé mon produit et j’ai appuyé pour prendre une photo et ça a crash direct``` 
1. New product
2. Click on "Front Picture"
3. Boom

Crash report sent: 
```
around 11:57 on an  iPhone XS
```

**Comment by aleene** [comment]
It works on my iPad. Somebody else have this issue as well?

**Comment by aleene** [comment]
![Screenshot 2019-10-14 at 15 13 05](https://user-images.githubusercontent.com/1329905/66753965-292f1500-ee95-11e9-9675-c509d8d79873.png)

**Comment by aleene** [comment]
Crash in:
`guard let productImage = ProductImage(barcode: barcode, image: image, type: imageType ?? .front) else {
            showErrorUploadingImage(forType: imageType)
            return
        }`

**Comment by aleene** [comment]
I have no idea why this would crash

**Comment by aleene** [comment]
Have we access to Crashlytics reports?

**Comment by teolemon** [comment]
no we don't. @Tovkal has. 
I have created a new Crashlytics account for Open Food Facts, so we can swap the id for the future. Or remove Crashlytics completely.

**Comment by aleene** [comment]
Let's change the id. I have no idea whether it is useful. No experience with it.

**Comment by aleene** [comment]
It seems the issue is with scanning a non-existing (new) product.

**Comment by aleene** [comment]
Code to set the barcode, was commented.

**Comment by Tovkal** [comment]
Crashlytics was originally set up on my personal account, but it is no longer working. Instead of setting up a new Crashlytics account it would be better to move directly to Firebase, as Fabric is deprecated due to being replaced by Firebase and will stop working at the end of March 2020.
