### ISSUE TITLE
Credits screen is white

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#378]
![image](https://user-images.githubusercontent.com/1689815/66831396-d36f7100-ef57-11e9-9c1f-d230da4012f9.png)

**Comment by aleene** [comment]
Seems I found this one in the code

**Comment by aleene** [comment]
Trouble finding where this is set.

**Comment by aleene** [comment]
This must be done in Credits.html and needs css code.

See also: https://stackoverflow.com/questions/57981661/ios-13-modifying-html-and-css-for-dark-mode-in-uiwebview

**Comment by aleene** [comment]
Seems solved, closing.
