### ISSUE TITLE
The splash screen and login modal are dark on iOS 12

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#381]
The splash screen and login modal are dark on iOS 12. It should be lite, unless the user has explicitely enabled darkmode.

**Comment by aleene** [comment]
Hmm works for me on IOS 13. We can try to force the background an see what happens on IOS 12.

**Comment by aleene** [comment]
Is les nice on IOS 13.

**Comment by aleene** [comment]
Seems solved

**Comment by teolemon** [comment]
Yes it is :star2:
