### ISSUE TITLE
Upload button are white (edit mode)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#383]
![image](https://user-images.githubusercontent.com/1689815/66834251-97d7a580-ef5d-11e9-97d3-8bbc0f0aa1e1.png)

**Comment by teolemon** [comment]
Also, the nutrient table has issues:
![image](https://user-images.githubusercontent.com/1689815/66834361-c35a9000-ef5d-11e9-99ec-4fe680689e2f.png)

**Comment by aleene** [comment]
Seems I must for the color here.

**Comment by aleene** [comment]
Where does this happen?
IconButtonView.xib - tertiairyBackgroundColor
