### ISSUE TITLE
Native credits

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#386]
**Summary:** 
Rewrite the credits viewcontroller, so that the credits will be native and not presented as webView. Might use a static TableViewController.

**Comment by davidlamys** [comment]
@aleene: Hey hey! I'd look into this. I think I'm going to bring the user to the profile pages of the respective authors' link when the user tap on the TableViewCell. Is that cool?

**Comment by davidlamys** [comment]
Also... do we want to remove snapkit?

**Comment by aleene** [comment]
Good question. We no longer use it?

**Comment by davidlamys** [comment]
We only use it in this view controller.

**Comment by aleene** [comment]
Well, if we use it we credit it. Seems a reasonable approach. Maybe we should add the other frameworks as well.

**Comment by davidlamys** [comment]
Oh, what I mean is that we will not use it anymore, after I rewrite the credits view controller. And after that, it won't be used anywhere.

Will it be better if we remove this dependency in our cartfile then? Or does the team think that keeping it might encourage people to use it?

**Comment by aleene** [comment]
Sounds good removing it.
