### ISSUE TITLE
Fully transparent scan

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#387]
**Summary:** 
The scan results after scanning are shown on a transparent page.

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/66907255-5997c000-f009-11e9-9ac6-2a8107fff435.png)
That's actually kind of cool :-P

**Comment by aleene** [comment]
I found the xib responsible for this background and adapted it. However it is embedded in another view, with a transparent background, which is difficult find. My computer is to slow to see the view stack

**Comment by aleene** [comment]
Responsible xib is: ScanProductSummaryView
