### ISSUE TITLE
Switch to HTTPS

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#4]
HTTPS is now live on OFF

**Comment by aleene** [comment]
This was already the case for the api (which I use). So what is the IOS impact?

**Comment by stephanegigandet** [comment]
It's also now in place for images etc. All http requests are being redirected to https, except for POST requests.

**Comment by Tovkal** [comment]
Using `https://ssl-api.openfoodfacts.org` as an endpoint, so we're already only using HTTPS.
