### ISSUE TITLE
Missing string in the new minerals list

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#400]
![image](https://user-images.githubusercontent.com/1689815/67141031-14b99680-f260-11e9-8d5b-87733579a5c9.png)
There's a missing string for minerals

**Comment by aleene** [comment]
Yes, and amino acids, other nutritional substances, ...

**Comment by teolemon** [comment]
@aleene 'product-detail.ingredients.mineral-list'

**Comment by aleene** [comment]
What do you mean?

**Comment by aleene** [comment]
case vitamins = "product-detail.ingredients.vitamins-list"
    case minerals = "product-detail.ingredients.minerals-list"
    case nucleotidesList = "product-detail.ingredients.nucleotides-list"
    case otherNutritionalSubstances = "product-detail.ingredients.otherNutritionalSubstances-list"

**Comment by aleene** [comment]
I am not able to recreated the localizable files as a non-standard approach to localization has been used.

**Comment by aleene** [comment]
A solution is to reintroduced the Apple method of localization.

**Comment by aleene** [comment]
In fact it is not possible to generate these files as there are calculated keys

**Comment by aleene** [comment]
The only fast solution I saw is to add every string by had to all languages file.

**Comment by teolemon** [comment]
I can confirm this now works. Thank you @aleene 💯
