### ISSUE TITLE
Add the number of additives to the scan card

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#405]
![image](https://user-images.githubusercontent.com/1689815/67151634-13708400-f2c9-11e9-8276-fcd378d4c848.png)

Add the number of additives (additives_n) to the scan card. Make all score bigger by removing the weight and the brand.

**Comment by aleene** [comment]
Should not be to difficult.

**Comment by davidlamys** [comment]
Hi @teolemon, what do you mean by this 'Add the number of additives' ?

Also is there any wiki that one should read to gain more understanding of the domain knowledge? Thank you

**Comment by davidlamys** [comment]
> Should not be to difficult. However it must be a translatable string. Image resizing is easy, as is deleting the fields.

This view is also reused when the user look at the product summary. Do we want to hide the Brand and Quantity labels there as well?

**Comment by davidlamys** [comment]
As a side discussion..are we gonna keep using MVC?

**Comment by aleene** [comment]
Look under the NOVA 4 in the mockup. It is extra data that must be shown and is to the taken from the json.

**Comment by aleene** [comment]
MVC yes, but see another issue #403.

**Comment by davidlamys** [comment]
> Look under the NOVA 4 in the mockup. It is extra data that must be shown and is to the taken from the json.

Got it. How about in the summary view. Do we remove the brand and and quantity in that screen as well?

**Comment by aleene** [comment]
Probably not. The idea is that in scan mode you get a quick evaluation, but later you need to see all

**Comment by davidlamys** [comment]
Alright. I think I have what I need to know :)

Last question: What happens when there are additives but no nova score? Shall we hide the whole column? 

And for the summary view,  I guess we will continue to show the number of additives as well?

**Comment by davidlamys** [comment]
As for the issue with nib. Since it's a reusable view, I'd try to just draw the whole thing out in code. probably should be done by end of this week.

**Comment by aleene** [comment]
If there is no nova, we still can show the additives. They are independent. And indeed a good idea to add it to the summary as well.

Can't you repurpose the existing xib?

**Comment by davidlamys** [comment]
Oh yes we can. I thought it'd be be easier to complete #403 if we no longer find xibs in the project.

will repurpose then.

**Comment by aleene** [comment]
I am more a fan of using the storyboard and not xibs. Gives me an overview of the app.
