### ISSUE TITLE
Image upload spinning wheel not honoring dark mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#407]
![image](https://user-images.githubusercontent.com/1689815/67160881-73147100-f355-11e9-9866-a1b54f34fec6.png)
Image upload spinning wheel not honoring dark mode

**Comment by aleene** [comment]
This might better work with other settings (.clear background and .label image color)

**Comment by aleene** [comment]
Seems solved, closing.
