### ISSUE TITLE
HTML version of the nutrition page is on a white background in dark mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#408]
![image](https://user-images.githubusercontent.com/1689815/67160895-a0f9b580-f355-11e9-8d91-2a87a9af9967.png)
Embedded HTML version of the nutrition page is on a white background in dark mode

**Comment by aleene** [comment]
Needs a css specialist. Or have a native interface.

**Comment by teolemon** [comment]
I don't think we embed a full html page in the html we send back. It should be about setting background-color="black", I guess.

**Comment by aleene** [comment]
I tried all possible combinations without help. On StackOverflow they pointed to a css solution.

**Comment by aleene** [comment]
Same as #388

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/api/v0/product/3302749508029.json?fields=nutrition_table_html

**Comment by teolemon** [comment]
```  
Or, set the webview's opaque property to NO .. and set the background of the view underneath to green.```

**Comment by teolemon** [comment]
[myWebView setBackgroundColor:[UIColor greenColor]];
[myWebView setOpaque:NO];
[myWebView loadHTMLString:myString baseURL:nil];
https://stackoverflow.com/questions/6605140/uiwebview-background-color

**Comment by aleene** [comment]
Great is was the opaque that I was missing.Now we only need to change the color of the text.

**Comment by aleene** [comment]
is solved
