### ISSUE TITLE
Dark mode edit mode issues

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#416]
![image](https://user-images.githubusercontent.com/1689815/67497354-234be780-f67e-11e9-83dc-481eaeb50b22.png)
![image](https://user-images.githubusercontent.com/1689815/67497379-2c3cb900-f67e-11e9-9a61-90e3027ecba4.png)

**Comment by aleene** [comment]
I probably missed this one (text color and background color).

**Comment by aleene** [comment]
Seems solved, closing.
