### ISSUE TITLE
Add a white/black line around ingredients field

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#417]
Add a hint where the ingredients are

![image](https://user-images.githubusercontent.com/1689815/67497689-a10ff300-f67e-11e9-938d-b3fc94c71e28.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/67498718-3bbd0180-f680-11e9-9d64-25cb04415f87.png)

**Comment by aleene** [comment]
Can use another background as well.

**Comment by aleene** [comment]
We need to rethink the color scheme and fonts used in this view. The actual content does not stand out at all. I'll try to use other text colors for the meta-data. And different background colors for the product data.

**Comment by aleene** [comment]
An approach to design of the interface. The view contains the following elements (with suggested colors):
- Headers (ingredients, etc.) == label
- Product Data == label
- Product Data labels (category:) == label
- Explanatory texts == secondaryLabel
- Status messages == tertiaryLabel

**Comment by aleene** [comment]
Seems solved, closing.
