### ISSUE TITLE
Your contributor account (Dark mode issue in white mode in ios 12)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#418]
![image](https://user-images.githubusercontent.com/1689815/67498332-8b4efd80-f67f-11e9-97f1-4c31f7bfba50.png)
Your contributor account (Dark mode issue in white mode in ios 12)

**Comment by aleene** [comment]
Probably not to difficult, if I can find it.

**Comment by aleene** [comment]
Seems solved, closing.
