### ISSUE TITLE
Dark mode issue for the Carbon impact

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#419]
![image](https://user-images.githubusercontent.com/1689815/67498492-d36e2000-f67f-11e9-826c-05d799181df5.png)
Dark mode issue for the Carbon impact in white mode on ios 12.
The background is slightly grey

**Comment by aleene** [comment]
Easy change. I have not the habit to check the icon backgrounds.

**Comment by aleene** [comment]
Seems solved, closing.
