### ISSUE TITLE
Making the edit button more accessible

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#421]
![image](https://user-images.githubusercontent.com/1689815/67506656-c1937980-f68d-11e9-97cb-ee2267af59da.png)
Now that we have a native edit mode, we can probably make the edit button more accessible

**Comment by aleene** [comment]
Notice that TWO buttons have been added to the mockup. Just one is ok. There is a subtle difference between the two standard buttons: one is **compose** (as used in the mail app) and means _create and edit_. the other one means just _edit_ an existing object. (Also the **+** icon is used for just _create without edit_).

**Comment by bredowmax** [comment]
In the iOS Calendar app, it just says 'Edit'.

That icon is not needed, I'd remove it. As aleene indicated: Because the user currently is always viewing an _already existing_ product, that 'compose' illustration would not the best possible solution here (it's the icon for _'start to write a new email'_

**Comment by pacocd** [comment]
hey,  I can help you with this one

**Comment by teolemon** [comment]
That would be great @pacocd 👌

**Comment by pacocd** [comment]
@teolemon where is share button supposed to be present in new design? is it about to be deleted?

**Comment by teolemon** [comment]
no, it's at the bottom of the page currently. It would be nice to move it at the top, like in the mockup above :-)

**Comment by pacocd** [comment]
@teolemon share is on navigation bar (right button) currently. Edit button is supposed to be part of navigation bar right button, but, what about share button? should it be deleted or is it going to be part of navigation bar too?

**Comment by aleene** [comment]
The pull request has a conflict.

I would add the share button there as well.

**Comment by aleene** [comment]
Is pull request #433

**Comment by jmtome** [comment]
Has this been done already? if not, I could help.

**Comment by aleene** [comment]
Please go ahead.

**Comment by jmtome** [comment]
> Please go ahead, I added you as assignee.

Hasn’t @pacocd done this already? What’s the issue with his pull request ?

**Comment by aleene** [comment]
Indeed I do not know what the issue is. Just a merge issue? Has is been finished? Does it work?

If you could investigate, it would be great.

**Comment by teolemon** [comment]
fixed by @aleene in the case of viewing the products in other scenarii than scans
