### ISSUE TITLE
Existing product name should populate Name field when editing Product information

### ISSUE THREAD

**Issue by SuzGupta** [openfoodfacts/openfoodfacts-ios#422]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker.](https://github.com/openfoodfacts/openfoodfacts-ios/issues)
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:** 

When attempting to edit a misspelled product name via iOS, the name does not appear as expected in the Name field of Product information.

**Steps to reproduce:** 
 - View a product. (In my case, I am using one from my History, "Enrichilada Sauce")
 - Tap Edit this product.
 -  Notice how the misspelled product name does not appear in the Name field.

**Expected behavior:** 

- All already entered data appears in the expected fields and is editable

**Observed behavior:** 

The product name has already been entered and is, in fact, what I want to edit, but it does not appear in the field. Instead, Name is empty. 

This is different behavior than editing on the web, where the product name field is correctly populated. See https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=0041501110386 and the screen cap below.

**Device and iOS version:** 

Apple iPhone 7+ running iOS 13.1.3

**Screenshots:** 

![ProductNameFilledInOnWeb](https://user-images.githubusercontent.com/5115383/67517952-52a42980-f669-11e9-8d54-5d54cc158017.jpg)

![ProductNameNotFilledOniOS](https://user-images.githubusercontent.com/5115383/67518091-a6167780-f669-11e9-82db-241078f2a0f4.png)

**Comment by aleene** [comment]
This seems also the case for the ingredients?

**Comment by aleene** [comment]
These are language dependent fields.

**Comment by aleene** [comment]
The issues is not really solved as we have to check how products with multiple languages work.

**Comment by bredowmax** [comment]
I've encountered a bug where I would add the name of a new product but when saving it, the name would not be saved. This is not a product that I edited, but a new one!

Language: German

**Comment by teolemon** [comment]
@SuzGupta @bredowmax can you confirm all your use cases now work ?

**Comment by aleene** [comment]
Seems solved, closing.
