### ISSUE TITLE
Dismiss the result card on swipe down

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#429]
Dismiss the result card on swipe down. This is a behaviour we already have on Android.
![image](https://user-images.githubusercontent.com/1689815/67636316-aa43ce80-f8cf-11e9-9f3c-cc4cbd270fde.png)

**Comment by aleene** [comment]
This probably should be set in `ScannerResultViewController` through the variable `topSummaryView.isHidden`.

**Comment by aleene** [comment]
In fact is does not happen in `ScannerResultViewController`. I can hide the the product summary, but an enclosing view remains.

**Comment by aleene** [comment]
I'll add a swipe up as well.
