### ISSUE TITLE
Unnecessary strings in XLIFF

### ISSUE THREAD

**Issue by yarons** [openfoodfacts/openfoodfacts-ios#43]
Please take a look at the crowdin options, there are many arguments and placeholders for translation, as you can see here (should not be available for translation):
https://github.com/openfoodfacts/openfoodfacts-ios/blob/master/xliff/en.xliff#L541

Thanks!

**Comment by teolemon** [comment]
@Tovkal ?

**Comment by yarons** [comment]
I'm just wondering if these can be removed or commented out as they are or should I also change something in other files other than strings.xml?
