### ISSUE TITLE
Transparency issue with NOVA score

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#431]
![image](https://user-images.githubusercontent.com/1689815/67636377-4ec61080-f8d0-11e9-9497-e045e69932d2.png)
In white mode, grey background behind NOVA

**Comment by bredowmax** [comment]
It's actually not dark mode but bright mode

**Comment by teolemon** [comment]
Yes, but code-wise, that's related (and caused by) changes around dark mode.

**Comment by teolemon** [comment]
It seems fixed. Thank you @aleene 👍
