### ISSUE TITLE
No internet Connection

### ISSUE THREAD

**Issue by DShivansh** [openfoodfacts/openfoodfacts-ios#44]
User is not notified when there is no internet connection when user is inside the app.

**Comment by SahilDhawan** [comment]
A Notification Banner can be used to add a prompt for internet connection. Reachability can be used to check for internet connection.
Something like this?

<img width="296" alt="screen shot 2018-02-17 at 12 29 42 am" src="https://user-images.githubusercontent.com/12775360/36324228-b57a06b2-1379-11e8-806a-c8bd59ecb658.png">

**Comment by DShivansh** [comment]
Yup 
I'll be adding the pr tuesday

**Comment by teolemon** [comment]
Rather than telling the user that he has no connexion, we should aim to make the app useful, even without connexion, by having an offline mode :-)
