### ISSUE TITLE
Remove unsecure URL

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#446]
``` 
    static let Server = "http://world.openfoodfacts.org/"
    static let SecureServer = "https://ssl-api.openfoodfacts.org/"
``` 

Remove unsecure URL and default to `https://world.openfoodfacts.org/`

**Comment by aleene** [comment]
So only one server should be used?

**Comment by aleene** [comment]
The SecureServer is not used any more, but the assignment was still there.
