### ISSUE TITLE
Main language is "English" while data is only selected in "French"

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#456]
https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=3701138800155
Main language is "English" while data is only selected in "French". This creates bad data whenever someone enters a new product.

Main language should be "French" while data is only selected in "French"

**Comment by aleene** [comment]
When a new product is created the app must assume the main language. Either it does this based on the interface language of the app, or on the locale of the app. I prefer the latter. I do not know what the app does at the moment.
But this can lead to the wrong assumption.

**Comment by teolemon** [comment]
It's doing neither one, nor another it seems.

**Comment by aleene** [comment]
I did a test, it defaults to the language of the apps interface. So is OK.

**Comment by TaciteOFF** [comment]
My iPhone is set to English US so every time I add picture, they're set to English. I'd rather have an in-app switch.

**Comment by aleene** [comment]
If you add an image, it should assume that you mean the primary language of the product and not invent a new language. (multiple languages are not yet supported)
