### ISSUE TITLE
Adding picture in offline mode deletes important data from OFF

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openfoodfacts-ios#457]
**Summary:** 

There's an issue when uploading pictures to product page from the "products you added while offline" page of the iOS app

**Steps to reproduce:** 

Please provide detailed steps for reproducing the issue.

 - Scan a new barcode to create a new product page from the app
 -  Add just one picture
- Edit the new product page from internet (add category)
 -  Lose connection / turn on Airplane mode
- Take more pictures
- Go back online and upload the pictures you took from the app
- The product page will be emptied, the category you added will be removed.

**Expected behavior:** 

It shouldn't delete anything

**Device and iOS version:** 

OpenFoodFacts beta (TestFlight) app 3.1 (26) 
iPhone XS  on iOS 13.2.2

**Comment by TaciteOFF** [comment]
@aleene @teolemon

**Comment by teolemon** [comment]
Closing in favor of #784
