### ISSUE TITLE
Back button not present when we are visiting the website in the app.

### ISSUE THREAD

**Issue by sgrpanchal31** [openfoodfacts/openfoodfacts-ios#46]
When we scan a barcode and the product is not present in the database, there is a hyperlink on the subsequent page that ask the user to add that product to the database linking to the openfoodfacts.org website. When we open the link, there is no way to go back to the app's main interface rather than restarting the app.

**Comment by Hrayr2112** [comment]
I am currently working on this bug. Please assign it to me.

**Comment by sgrpanchal31** [comment]
Sorry mate but I am just an another enthusiast developer like you. 
@teolemon help this guy

**Comment by teolemon** [comment]
@sgrpanchal31 have you started developping the feature ?

**Comment by sgrpanchal31** [comment]
Actually I am working on the data science project for classifying products automatically. I was using the the app to get familiar with the product and eventually found some bugs on the way.

**Comment by teolemon** [comment]
@Hrayr2112 You may work on this one, then :-)

**Comment by teolemon** [comment]
@sgrpanchal31 Nice, you built the new app instead of just trying the one currently in the app store ?

**Comment by sgrpanchal31** [comment]
@teolemon No I was using the one from the app store itself, but I did it's testing on my xcode once.

**Comment by snuff4** [comment]
Hi @teolemon again! I tested this on both the apps, and yes this problem is there in the current app from the App Store, but taking pictures and adding basic details has been integrated in the Swift app.
So we can close this issue.

**Comment by teolemon** [comment]
@snuff4 great. closing then.
