### ISSUE TITLE
Crash when switching between

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#466]
1) Launch app 
2) from Search view, click Settings 
3) click on Your contributor account 
4) click Search 
5) click on Settings

Boom. The app crashes. Reproduced 3 times by Tacite

**Comment by aleene** [comment]
Can not confirm this on my iPad in several modes. Need other input to solve this.

**Comment by aleene** [comment]
There was a crash report, which pointed to a line. I'll repair and see if it still occurs.
