### ISSUE TITLE
Nova row in case of no nova

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#475]
**Summary:** 
If no nova is available, the row in the ingredients tab is only half filled. Can be nicer.

**Comment by teolemon** [comment]
Can you provide a screenshot ?

**Comment by aleene** [comment]
![IMG_1064](https://user-images.githubusercontent.com/1329905/69476944-6f568d00-0de0-11ea-8649-bfea328f1a8e.jpeg)

**Comment by aleene** [comment]
With nova. Still needs the appropriate explanations.

**Comment by teolemon** [comment]
Can we replace NOVA 1 by  the official wording ?
https://world.openfoodfacts.org/nova-groups.json
1 - Unprocessed or minimally processed foods
2 - Processed culinary ingredients
3 - Processed foods
4 - Ultra processed food and drink products

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/69477019-75993900-0de1-11ea-9dd2-696842b7a7f7.png)

**Comment by aleene** [comment]
Is done now
