### ISSUE TITLE
Pending items upload not refreshing after uploading the items.

### ISSUE THREAD

**Issue by juanca8520** [openfoodfacts/openfoodfacts-ios#486]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker.](https://github.com/openfoodfacts/openfoodfacts-ios/issues)
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:** 

TableView not being refreshed after uploading the pending products, it's required to manually reload the view (Go back and enter again)

**Steps to reproduce:** 

Please provide detailed steps for reproducing the issue.

 - Put phone in airplane mode 
 -  Add a new product
 -  Upload the pending product after turning airplane mode off

**Expected behavior:** 

What did you expect the app to do?
Automatically refresh the tableView after uploading the items.

**Observed behavior:** 

What did you see instead?  Describe your issue in detail here.
The uploaded item stayed in the tableView.

**Device and iOS version:** 

Apple iPhone [Device name] running iOS [Version number]
iPhone 8 running iOS 13.2.3

**Screenshots:**

**Comment by aleene** [comment]
Need to send a notification after a successful upload and the tableView must refreshed after receiving that.

**Comment by aleene** [comment]
Guess it is enough to add a reload in:
```
if progress < 1.0 {
   SVProgressHUD.showProgress(progress, status: "pending-upload.hud.status".localized)
} else {
```
