### ISSUE TITLE
Reusing the Nutriscore component from aleene

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#5]
https://github.com/aleene/NutriScoreLogo

**Comment by Tovkal** [comment]
Already using it in the nutrition view, but there seems to be a bug when rotating. I see there's an issue for that, https://github.com/aleene/NutriScoreLogo/issues/1, will check it out and see if I can fix it and submit a PR.

**Comment by aleene** [comment]
Check also the scaling, I am not yey happy with it, and am still fiddling with the numbers.
