### ISSUE TITLE
Black camera icon

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#500]
Camera icon does not adapt to dark mode. What screen is this? There is no black camera any more (?).

**Comment by teolemon** [comment]
![IMG_7002](https://user-images.githubusercontent.com/1689815/70355628-ed03a980-1872-11ea-8642-22d18a1a30f1.PNG)

**Comment by aleene** [comment]
I understand now, I was using a version where I had already changed the icons. Forgot to commit.
