### ISSUE TITLE
NOVA explanation still hidden.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#507]
Is it possible to remove the right and left margins ?
![image](https://user-images.githubusercontent.com/1689815/70391318-2acc1380-19d4-11ea-92bd-0f7d16d8593d.png)

**Comment by aleene** [comment]
Which ones?

**Comment by aleene** [comment]
There are two transforms in the code:

        `novaGroup <- (map[OFFJson.NovaGroupKey], IntTransform())`
and
        `novaGroup <- map[OFFJson.NovaGroupKey]`

why?

**Comment by aleene** [comment]
The whole stackView row should grow with the number of lines.

**Comment by aleene** [comment]
![IMG_1080](https://user-images.githubusercontent.com/1329905/70393755-d03fb100-19ed-11ea-9e03-2748705f33a7.jpeg)
It scales now.
