### ISSUE TITLE
The login button is always greyed out

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#508]
![image](https://user-images.githubusercontent.com/1689815/70391338-5fd86600-19d4-11ea-9cf1-f5dca791c921.png)
The login button is greyed out.

**Comment by aleene** [comment]
It seems you entered your password? If username and password are available, the button should enable itself.

**Comment by aleene** [comment]
As soon as you type the first letter of the password, the button will be enabled.
