### ISSUE TITLE
NOVA appears randomly

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#509]
NOVA groups appear randomly. This is probably because we use the nutriment value of NOVA instead of the normalized value.
![image](https://user-images.githubusercontent.com/1689815/70391382-d8d7bd80-19d4-11ea-9b0d-f68289c6ca5e.png?w=50|width=100px)

Barilla Lasagne
![image](https://user-images.githubusercontent.com/1689815/70391387-e2612580-19d4-11ea-9cb8-ba24efd890a9.png)
https://fr.openfoodfacts.org/produit/8076800376999/pates-aux-oeufs-lasagne-barilla
https://world.openfoodfacts.org/api/v0/product/8076800376999.json?fields=nova-group,nova-group_100g,nova-group_serving,nova_group,nova_groups_tags,nova_group_debug,nutriments
```{"code":"8076800376999","status":1,"status_verbose":"product found","product":{"nova_groups_tags":["en:1-unprocessed-or-minimally-processed-foods"],"nova_group":1,"nova_group_debug":"","nutriments":{"sodium_unit":"g","sugars_value":3,"sodium":0.03,"energy-kcal":1536,"nova-group_serving":1,"saturated-fat":1.2,"nutrition-score-uk_100g":-3,"proteins_value":14,"nova-group":1,"carbohydrates_100g":67.3,"fiber_value":3,"proteins_unit":"g","sugars_unit":"g","nova-group_100g":1,"sugars_100g":3,"energy":1549,"fiber_100g":3,"salt_unit":"g","carbon-footprint-from-known-ingredients_product":252,"energy_value":1549,"fat_100g":4,"fat":4,"energy-kcal_value":367,"proteins":14,"proteins_100g":14,"fiber_unit":"g","energy-kcal_unit":"kcal","sodium_100g":0.03,"salt_100g":0.075,"nutrition-score-fr_100g":-3,"saturated-fat_100g":1.2,"sugars":3,"sodium_value":0.03,"energy-kj_100g":1549,"carbohydrates_value":67.3,"saturated-fat_value":1.2,"energy-kj_unit":"kJ","fat_value":4,"fiber":3,"carbohydrates_unit":"g","energy_unit":"kJ","energy_100g":1549,"salt_value":0.075,"energy-kj":1549,"carbohydrates":67.3,"nutrition-score-fr":-3,"fat_unit":"g","energy-kcal_100g":1536,"carbon-footprint-from-known-ingredients_100g":50.336,"nutrition-score-uk":-3,"saturated-fat_unit":"g","energy-kj_value":1549,"salt":0.075}}}``` 

https://fr.openfoodfacts.org/produit/3270160420186/tarte-aux-framboises-picard
https://world.openfoodfacts.org/api/v0/product/3270160420186.json?fields=nova-group,nova-group_100g,nova-group_serving,nova_group,nova_groups_tags,nova_group_debug,nutriments
```{"status_verbose":"product found","status":1,"code":"3270160420186","product":{"nova_group":"3","nova_group_debug":" -- ingredients/en:salt : 3","nova_groups_tags":["en:3-processed-foods"],"nutriments":{"sodium":0.036,"sugars_value":22,"saturated-fat_serving":3.73,"sodium_unit":"g","energy_serving":778,"energy-kcal":937,"nova-group_serving":3,"sugars_serving":18.3,"nutrition-score-fr_serving":6,"saturated-fat":4.5,"nutrition-score-uk_100g":6,"proteins_value":2.7,"nova-group":3,"carbohydrates_100g":37,"fiber_value":3.5,"proteins_unit":"g","nova-group_100g":3,"sugars_unit":"g","sugars_100g":22,"energy":937,"carbon-footprint-from-known-ingredients_serving":45.8,"fiber_100g":3.5,"carbohydrates_serving":30.7,"salt_unit":"g","carbon-footprint-from-known-ingredients_product":276,"energy-kcal_serving":778,"energy_value":224,"fat_100g":6.6,"fat":6.6,"fiber_serving":2.91,"energy-kcal_value":224,"proteins":2.7,"proteins_100g":2.7,"sodium_100g":0.036,"fiber_unit":"g","energy-kcal_unit":"kcal","salt_100g":0.09,"nutrition-score-fr_100g":6,"sodium_value":0.036,"saturated-fat_100g":4.5,"sugars":22,"carbohydrates_value":37,"sodium_serving":0.0299,"proteins_serving":2.24,"saturated-fat_value":4.5,"fat_value":6.6,"salt_serving":0.0747,"fiber":3.5,"energy_100g":937,"carbohydrates_unit":"g","salt_value":0.09,"energy_unit":"kcal","carbohydrates":37,"nutrition-score-uk_serving":6,"nutrition-score-fr":6,"energy-kcal_100g":937,"fat_unit":"g","carbon-footprint-from-known-ingredients_100g":55.21,"nutrition-score-uk":6,"saturated-fat_unit":"g","fat_serving":5.48,"salt":0.09}}}```

**Comment by teolemon** [comment]
```
{“code”:“8076800376999",“status”:1,“status_verbose”:“product found”,“product”:{“nova_groups_tags”:[“en:1-unprocessed-or-minimally-processed-foods”],“nova_group”:1,“nova_group_debug”:“”,“nutriments”:{“nova-group_serving”:1,,“nova-group”:1,“nova-group_100g”:1}}}
```
```
{“status_verbose”:“product found”,“status”:1,“code”:“3270160420186”,“product”:{“nova_group”:“3",“nova_group_debug”:” -- ingredients/en:salt : 3",“nova_groups_tags”:[“en:3-processed-foods”],“nutriments”:{“nova-group_serving”:3,“nova-group”:3,“nova-group_100g”:3}}}
```
Here they both are, edited for simplicity
in one of them; NOVA group is returned as an INT, in the other as a STR
so it’s the same bug I thought we already solved server side, and client side

**Comment by aleene** [comment]
So we leave it as a sever issue?

**Comment by teolemon** [comment]
we're discussing in the release channel. I see that the client-side INT protection is not working either.

**Comment by aleene** [comment]
For FoodViewer I had to add protections for many fields. Not very good, is all unnecessary overhead for the server not working well.

**Comment by aleene** [comment]
There are two transforms in the code:

        `novaGroup <- (map[OFFJson.NovaGroupKey], IntTransform())`
and
        `novaGroup <- map[OFFJson.NovaGroupKey]`

why?

**Comment by aleene** [comment]
It is also repaired on the server side. Did that help?

**Comment by teolemon** [comment]
Clicking on each item of my history refreshes it and solves the issue. 
Do we have a method to force the refresh of the whole history ?
Otherwise, we can consider the case closed

**Comment by aleene** [comment]
> Do we have a method to force the refresh of the whole history ?
Not that I know of
