### ISSUE TITLE
Can't make an account on the app.

### ISSUE THREAD

**Issue by sgrpanchal31** [openfoodfacts/openfoodfacts-ios#51]
When we try to create an account throught "create an account" hyperlink in Sign-in Section, it redirects to the openfoodfacts.org's homepage.

**Comment by teolemon** [comment]
The url should be https://world.openfoodfacts.org/cgi/user.pl

**Comment by snuff4** [comment]
Hi @teolemon, I used both the apps on a physical device, and observed that the issue is in the app currently on the App Store, NOT with the  Swift application.

So we can close this issue.

**Comment by teolemon** [comment]
thanks @snuff4
