### ISSUE TITLE
Country are not properly displayed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#515]
![image](https://user-images.githubusercontent.com/1689815/70397166-2887aa80-1a10-11ea-908e-da0881d6ca8c.png)

**Comment by teolemon** [comment]
EN is invalid, but en:it should be displayed as Italy
https://world.openfoodfacts.org/product/5999076214020/biotech-usa-protein-fusion-85-ricotta

**Comment by aleene** [comment]
Have to see where `en:it` comes from. Is that in the data, or does the app do something?

**Comment by aleene** [comment]
![Screenshot 2019-12-09 at 14 02 12](https://user-images.githubusercontent.com/1329905/70437733-88239b80-1a8c-11ea-9687-75c93b7cdb42.png)
The `en:it` is in the data as entered by the user.

**Comment by teolemon** [comment]
Ideally, we should use `countries_tags` field and map using the countries taxonomy
`https://static.openfoodfacts.org/data/taxonomies/countries.json`

**Comment by aleene** [comment]
But then you will keep the errors in the original field. The original field is also not visible on the web-site. Will be very hidden that way and will never be repaired.

**Comment by aleene** [comment]
We could use they tags fields for viewing and the original fields for editing.

**Comment by aleene** [comment]
I realised that the country field can not be edited, it is not presented. So I will change over to the tags field.

**Comment by aleene** [comment]
Turns out we did not use the countries taxonomy either.
