### ISSUE TITLE
The nutrition table is displayed even if state is nutrition to be completed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#517]
![image](https://user-images.githubusercontent.com/1689815/70397202-7a303500-1a10-11ea-9106-4995f959b554.png)
The nutrition table is displayed even if state is nutrition to be completed. We should probably hide the table in that case, and put a button "Help complete nutrition facts"

**Comment by aleene** [comment]
Sounds good. Wonder how to detect it? I think the states are not extracted from the json at the moment.
