### ISSUE TITLE
Add a "Password forgotten" link that opens the password reset page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#52]
Add a "Password forgotten" link that opens the password reset page

https://world.openfoodfacts.org/cgi/reset_password.pl

**Comment by snuff4** [comment]
Hi @teolemon , can you review if it is okay?

![simulator screen shot - iphone x - 2018-02-21 at 19 52 48_iphonexspacegrey_portrait](https://user-images.githubusercontent.com/30552772/36485208-9cbc26de-1741-11e8-82cf-15ca703eb3e4.png)

![simulator screen shot - iphone x - 2018-02-21 at 19 52 56_iphonexspacegrey_portrait](https://user-images.githubusercontent.com/30552772/36485210-9e99f972-1741-11e8-812d-29ba57ed0ab9.png)

**Comment by snuff4** [comment]
Edited, and now used the openUrlInApp to get the link.

![simulator screen shot - iphone x - 2018-02-21 at 20 07 43_iphonexspacegrey_portrait](https://user-images.githubusercontent.com/30552772/36485926-4d92e730-1743-11e8-8c45-e62217c78ad1.png)
