### ISSUE TITLE
The app crashes when clicking on "Cancel" in the edit view

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#533]
The app crashes when clicking on "Cancel" in the edit view.
Reported by Tacite. He sent a crash report.

**Comment by aleene** [comment]
Have to look at the crash report. Works with me.

**Comment by aleene** [comment]
The crash is the same as #527

**Comment by aleene** [comment]
I'll add a check to prevent a possible crash. Will not be a final solution.

**Comment by aleene** [comment]
I had this crash as well. It happens as one edits a new product.
