### ISSUE TITLE
Add a prompt to extract Ingredients when photo is already present

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#537]
**Summary:** 
@raturina:
`Also if there’s an ingredient picture there should always be a button to trigger ingredient extraction. If there‘s a pic not added through the app, this button is not there. `

**Comment by teolemon** [comment]
I have made mockups in a previous bug:
https://github.com/openfoodfacts/openfoodfacts-ios/issues/171
