### ISSUE TITLE
Ingredient analysis is broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#548]
**Screenshots**
![image](https://user-images.githubusercontent.com/1689815/71770187-0bb89700-2f2a-11ea-93e6-51e5681cead4.png)

**Summary:** 
The ingredient analysis is blank, and clicking on the icon space sends empty popups.

**Steps to reproduce:** 

 - Scan a product with ingredients completed
 -  Slide up
 -  Look at the main tab

**Expected behavior:** 

Red, grey and green icons should appear, depending on the vegan / vegetarian / palm oil status, and more insight should appear on click.

**Device and iOS version:** 

Apple iPhone 5S running iOS 12

**Comment by aleene** [comment]
The functionality works. However this requires the refresh of the taxonomies. Re-installing the app helps for this.

**Comment by teolemon** [comment]
What's our current taxonomy refresh mechanism for iOS ? on app reinstall ? monthly ? on server file update ?

**Comment by aleene** [comment]
Normal refresh is once per month. I'll see if I can make an exception if a taxonomy is missing.
