### ISSUE TITLE
Disable search as you type: it does not work and causes performance issues on the server

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-ios#553]
The app currently sends a search query to the server for each character typed by the user in the search box:

---  1579086525      25322   h - map:  - graph:  - download:        page: 1  count:
---  1579086525      25317   ha - map:  - graph:  - download:       page: 1  count:
---  1579086525      25294   ham - map:  - graph:  - download:      page: 1  count:
---  1579086526      25322   hamb - map:  - graph:  - download:     page: 1  count:
---  1579086526      25302   hambur - map:  - graph:  - download:   page: 1  count:
---  1579086528      25317   hamburger char - map:  - graph:  - download:    page: 1 count:
---  1579086528      25302   hamburger charal - map:  - graph:  - download:  page: 1 count:

This does not work: the server does not support searching on parts of words, so the results will be bogus. Plus it makes useless queries to the server.

Please either disable search as you type, or only send a query when the user types a space, so that we have whole words.

**Comment by stephanegigandet** [comment]
Plus it actually prevent us from building a useful search as you type feature: if we have only whole queries in the search logs, then we can use them to build a working such as you type feature.

**Comment by chaubss** [comment]
Hi, I would like to work on this issue.

**Comment by teolemon** [comment]
Hi @chaubss I just assiged the issue to you 👍

**Comment by chaubss** [comment]
Thanks, I have made a pull request which fixes this. Could you please review it?
