### ISSUE TITLE
Loop of analysis logos

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#559]
![IMG_1164](https://user-images.githubusercontent.com/1329905/73252843-b899d300-41bb-11ea-8bcd-7d7c66f0098f.png)
Is in latest master.

**Comment by philippeauriach** [comment]
Its beautiful :) 
Do you have any steps to reproduce ? Or is it on this product in particular ?

**Comment by aleene** [comment]
Pull down the product page.

**Comment by philippeauriach** [comment]
It is a recylcing cell issue, I forgot to empty it before adding the new ones. fixing that right away
