### ISSUE TITLE
Floating ingredient analysis icons appear when no barcode is detected

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#569]
**Summary:** 
ingredient analysis are shown, when no barcode is detected. Is this the correct placement of the icons? They also appear on a positive scan result.
![IMG_1174](https://user-images.githubusercontent.com/1329905/73656403-54ca4b00-4690-11ea-8d6d-019b72eb3391.png)

**Steps to reproduce:** 
In scanner-mode, just wait and they appear if no barcode has been found. It seems to show the icons for the previous product. 

**Device and iOS version:** 

Apple iPad latest build

**Screenshots:**

**Comment by teolemon** [comment]
@aleene is this fixed ?

**Comment by aleene** [comment]
What part? The icons are ok, the placement stays the same.

**Comment by teolemon** [comment]
You mean that you see the icons, even when there's no barcode ?

**Comment by aleene** [comment]
This is solved, I did not see it anymore.
