### ISSUE TITLE
Add a link to the webversion for power users

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#573]
``` 
Suggestion pour l’app iOS 
@OpenFoodFactsFr
 : pouvoir aller sur la fiche produit Web depuis la fiche produit de l’app. Ça permettrait notamment de voir les dates d’ajout et de modif, les moyennes nutritionnelles ou les auteurs des photos.
```

be able to go to the web product page from the app's product page. This would allow you to see the dates of addition and modification, nutritional averages or the authors of the photos.

**Comment by aleene** [comment]
This should be part of the share button. #61 and #64.

**Comment by aleene** [comment]
We already have the share button, but adding safari requires some extra work.

**Comment by aleene** [comment]
![IMG_1208](https://user-images.githubusercontent.com/1329905/75362234-b741f000-58b8-11ea-9e36-cbd74f199cf6.jpeg)
