### ISSUE TITLE
Nag for ingredients when photo added but ingredients not extracted

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#575]
![image](https://user-images.githubusercontent.com/1689815/73787527-c93de080-479b-11ea-95e5-3d36a428402d.png)

Nag for ingredients when photo added but ingredients not extracted

**Comment by teolemon** [comment]
3270160861880

**Comment by aleene** [comment]
What is exactly the issue?

**Comment by teolemon** [comment]
Normally, we should have grey boxes that, when clicked, suggest you to add the ingredients

**Comment by teolemon** [comment]
fixed in trunk, but not in the testflight release. sorry for the noise
