### ISSUE TITLE
Can't exit product edition

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#580]
Happens when coming from ingredient analysis, but possibly in other scenarii.
Steps to reproduce in this video: 
https://photos.app.goo.gl/VArjpock2VEJ3riQ9

**Comment by philippeauriach** [comment]
the "save" button in the upper right is only to save, it does not dismiss the view (same as if you clicked on a "save" button inside the form). To quit the form the button "cancel" works for me, does it for you ? Maybe we should rename it to "back" or "done"

**Comment by teolemon** [comment]
The expected behaviour (I guess?) is to autosave on close.

**Comment by philippeauriach** [comment]
Ok so save and close when tapping on save ?

**Comment by philippeauriach** [comment]
Do we wait for the save to complete or we quit right away ?

**Comment by teolemon** [comment]
if we can quit right away and complete the save in the background, all the better, but that would require a refresh ?

**Comment by philippeauriach** [comment]
a refresh ?

**Comment by teolemon** [comment]
in those cases, the user expects a result (vegan status, nutriscore…)
So if he/she hits save and see nothing, this is disappointing

**Comment by philippeauriach** [comment]
Yes understood. We could launch a notification from the background when the update is done, and if the product is still displayed, then we reload. Coding that
