### ISSUE TITLE
Improve the layout of ingredient analysis

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#585]
![image](https://user-images.githubusercontent.com/1689815/74163496-c3744f00-4c22-11ea-8ec4-72bd20d8b30e.png)

Propositions to improve the layout of ingredient analysis

**Comment by aleene** [comment]
Is this an issue of library as well?

**Comment by teolemon** [comment]
No, just some padding missing in the layout I think. 
cc @philippeauriach

**Comment by philippeauriach** [comment]
Some padding and also compression resistance of the label, currently fixing this
