### ISSUE TITLE
Add the "Generic name" of the product in the summary view

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#59]

**Comment by snuff4** [comment]
Hi @teolemon , can you elaborate on this, or give an example please?

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/product/3245550078735/snack-poppe-saveur-barbecue-too-good
```Common name: Snack soufflé a base de soja et pomme de terre saveur barbecue``` 
```generic_name : name that shouldn't contain brands : Cola soda
generic_name_LANG_CODE : name that shouldn't contain brands:
generic_name_fr:soda au cola
generic_name_en:cola soda```
https://en.wiki.openfoodfacts.org/API#Name

**Comment by MayankR** [comment]
Hi, I've just downloaded the repo and started playing around with it. I would like to solve this issue. I have been able to add the generic name of the product to the table list in the summary page, as shown in the attached image.
1) In terms of UI, is this how the generic name is supposed to be added to the summary page, or in some other manner?
2)There is a LANG_CODE with generic_name too, I'd like to know which one would we like to show by default ?
![simulator screen shot - iphone 8 - 2018-02-26 at 16 40 49](https://user-images.githubusercontent.com/6612991/36667435-d72d093e-1b13-11e8-9b58-d8f831fcb69f.png)

**Comment by teolemon** [comment]
The generic name can be available in several languages. You should display the common name in the language of the UX, if not available English, and if not available, the main language of the product. In terms of position,Your current implementation is the right one.

**Comment by Abishek10** [comment]
@teolemon Can i work on this ?

**Comment by snuff4** [comment]
@MayankR Hi, Are you still working on this issue? 
If no, I would like to work on it.
