### ISSUE TITLE
HTML characters in the product name

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#593]
It seems that in some cases, there are some HTML characters in the product name. The app is not digesting it well.
ean13-8717163809570
off-8717163809570

![image](https://user-images.githubusercontent.com/1689815/74608345-7b50a300-50e0-11ea-9a1a-20ccaed5bb47.png)

**Comment by teolemon** [comment]
cc @stephanegigandet

**Comment by aleene** [comment]
I think the &quot; is also in the json.

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/74609175-da65e600-50e7-11ea-8f89-53433022a925.png)
![image](https://user-images.githubusercontent.com/1689815/74609177-e2258a80-50e7-11ea-96dd-bf1c5cbce33d.png)
The behaviour is barely better in Android…

**Comment by punss** [comment]
Is anybody actively working on this or would it be alright for me to go ahead and fix it?

**Comment by teolemon** [comment]
I just assigned the issue to you @punss 👍

**Comment by aleene** [comment]
The solution adopted hangs the app #605

**Comment by teolemon** [comment]
depriorizing: small subset of products
