### ISSUE TITLE
Units not appearing in edit mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#601]
Clicking on it works, so it seems to be a dark mode issue. Product: 3560070846788
![image](https://user-images.githubusercontent.com/1689815/75118718-c3da0480-567c-11ea-9a35-6f13d446e0f1.png)

**Comment by teolemon** [comment]
Clicking on it works, so it seems to be a dark mode issue

**Comment by aleene** [comment]
Seems I can not confirm this.

**Comment by teolemon** [comment]
@aleene can you share a screenshot ?

**Comment by aleene** [comment]
Not convinced?
![IMG_1205](https://user-images.githubusercontent.com/1329905/75345695-81434280-589d-11ea-89ae-7cde40762f1f.jpeg)

**Comment by teolemon** [comment]
just trying to find the root cause. And it looks more and more like a STR vs INT issue :-(

**Comment by teolemon** [comment]
(or something of the likes)

**Comment by teolemon** [comment]
I think Tacite told me it was anyway clickable. Do we change the color in some cases ?

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/75346145-60c7b800-589e-11ea-8c16-62fc51bd96f0.png)

**Comment by teolemon** [comment]
Tacite is still able to reproduce on this one

**Comment by aleene** [comment]
Yep, it is related to the product.

**Comment by aleene** [comment]
In fact the data is not available in the json, so the app shows what is there and makes no assumptions.

**Comment by teolemon** [comment]
can you paste the related snippet of the JSON. cc @stephanegigandet

**Comment by aleene** [comment]
`"nutriments":{"nutrition-score-fr":3,"energy-kcal_value":172,"energy_100g":720,"sugars_unit":"","fat_100g":10,"salt_100g":0.94,"energy-kcal":720,"nutrition-score-fr_100g":3,"nova-group":3,"salt_unit":"","energy":720,"energy-kcal_100g":720,"saturated-fat_unit":"","carbohydrates_unit":"","energy_serving":2160,"energy-kcal_unit":"kcal","sugars_100g":0.6,"proteins_serving":28.5,"sodium_value":0.376,"fiber":1.6,"fiber_value":1.6,"fat":10,"sugars_serving":1.8,"fat_value":10,"proteins_100g":9.5,"sodium_unit":"g","fat_unit":"","saturated-fat_serving":11.1,"saturated-fat":3.7,"carbon-footprint-from-known-ingredients_100g":154.84,"saturated-fat_value":3.7,"carbohydrates_100g":10,"nova-group_serving":3,"fat_serving":30,"nova-group_100g":3,"carbohydrates_value":10,"sugars_value":0.6,"fiber_serving":4.8,"salt_value":0.94,"carbohydrates_serving":30,"sodium_serving":1.13,"sugars":0.6,"nutrition-score-uk":3,"saturated-fat_100g":3.7,"carbon-footprint-from-known-ingredients_serving":465,"salt":0.94,"salt_serving":2.82,"carbon-footprint-from-known-ingredients_product":465,"proteins":9.5,"energy_unit":"kcal","proteins_unit":"","energy_value":172,"fiber_unit":"g","carbohydrates":10,"sodium_100g":0.376,"energy-kcal_serving":2160,"sodium":0.376,"proteins_value":9.5,"nutrition-score-uk_100g":3,"fiber_100g":1.6}`

**Comment by teolemon** [comment]
thanks :-)

**Comment by aleene** [comment]
sugars_unit":"",
"salt_unit":"",
"saturated-fat_unit":"",
"carbohydrates_unit":"",
"sodium_unit":"g",
"fat_unit":"",
"energy_unit":"kcal",
"proteins_unit":"",
"fiber_unit":"g",

for easier readability

**Comment by teolemon** [comment]
Also reported against the server @aleene 
https://github.com/openfoodfacts/openfoodfacts-server/issues/2955

**Comment by stephanegigandet** [comment]
@aleene : the app must not use the fields *_unit and *_value, they are for internal use only (they contain whatever the last user or app entered, they are not normalized in any way, and they can be empty an app does not send an unit).

The only fields the app should use are the *_100g and *_serving fields.

**Comment by aleene** [comment]
OK, I forgot about that distinction. We'll repair it.

**Comment by teolemon** [comment]
https://barcode.tec-it.com/fr/EAN13?data=3560070100484

**Comment by aleene** [comment]
If the nutritional values exist already, use the standard units. The user can change these if needed.
