### ISSUE TITLE
Dark mode issue for questions

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#603]
![image](https://user-images.githubusercontent.com/1689815/75119088-21bc1b80-5680-11ea-8d2c-92a16c81cff0.png)

**Comment by aleene** [comment]
What is the issue. the colour .blue stays blue in dark mode.

**Comment by teolemon** [comment]
You can't see the Yes/No/Maybe text below the 3 icons.

**Comment by aleene** [comment]
The culprit:
`
button.titleLabel?.textColor = UIColor.black
`

**Comment by aleene** [comment]
Solution:
`            if #available(iOS 13.0, *) {
                button.titleLabel?.textColor = UIColor.label
                button.backgroundColor = UIColor.systemFill
            } else {
                button.titleLabel?.textColor = UIColor.black
                button.backgroundColor = UIColor.darkGray
            }
`

**Comment by teolemon** [comment]
closing this one following your fix @aleene

**Comment by aleene** [comment]
I am not sure these are the right colours:
![IMG_1204](https://user-images.githubusercontent.com/1329905/75345624-5ce76600-589d-11ea-80dc-de65759a62df.jpeg)

**Comment by teolemon** [comment]
I'm not either. good catch.

**Comment by aleene** [comment]
What should it look like? Black on white in non-dark?

**Comment by teolemon** [comment]
yup

**Comment by aleene** [comment]
And blue on black in dark.

(I found at last a product that offers the questions.)

**Comment by aleene** [comment]
![IMG_1206](https://user-images.githubusercontent.com/1329905/75346026-1a725900-589e-11ea-865a-474c294728a9.jpeg)
