### ISSUE TITLE
Impossible to open products from history

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#604]
![ezgif-3-29e8dd2003cd](https://user-images.githubusercontent.com/1689815/75119402-e242fe80-5682-11ea-819b-7daa60459991.gif)

**Comment by aleene** [comment]
Annoying. The app progresses to the pushDetail, but then nothing happens.

**Comment by aleene** [comment]
It seems it happens in the String extension, which gets rid of the html encoding:

``
    var htmlDecoded: String {
        let decoded: String? = nil
            //try? NSAttributedString(data: Data(utf8), options: [
            //.documentType: NSAttributedString.DocumentType.html,
            //.characterEncoding: String.Encoding.utf8.rawValue
        //], documentAttributes: nil).string

        return decoded ?? self
    }

``
Documenting it out solves it.

**Comment by teolemon** [comment]
closing following merged fix by @aleene
