### ISSUE TITLE
Crash in setText for label

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#609]
**Summary:** 

![Screenshot 2020-02-25 at 17 42 59](https://user-images.githubusercontent.com/1329905/75267286-56ea7a00-57f6-11ea-8a3b-e1fd084e92df.png)

**Comment by aleene** [comment]
The explanation is not very clear. I assume the crash is due to the fact the UILabel is nil.

**Comment by philippeauriach** [comment]
Doing the PR review I looked into it, and found some insights : 

From the stack trace it seems that it happens in a closure inside viewDidLoad, so when the offlineStatus change. 
There is something weird here, in the fact that the observeToken is stored but never used to stop listening. My guess is that the viewController disappear at some time, so the view is released, but the offline listener still try to trigger an update, which means the view is indeed nil. 

The proper fix in this case is to call `observeNotificationToken?.invalidate()` in `viewWillDisappear`, and move the following in viewWillAppear : 
```
self.observeNotificationToken = self.offlineStatus.observe { (_) in 
  self.updateInitialView() 
} 
self.updateInitialView()
```

**Comment by aleene** [comment]
Great analysis.

**Comment by aleene** [comment]
I'll added your suggestions.

**Comment by teolemon** [comment]
can we close this one as a result of the merge ?

**Comment by aleene** [comment]
We are not sure whether this really solved the issues, but lets close and open when it is not solved.

**Comment by philippeauriach** [comment]
@aleene  I just thought of something else, regarding the same subject (it won't change the result but it's good practice): we should use weak self in the closure to not retain the VC : 
```
self.observeNotificationToken = self.offlineStatus.observe { [weak self] (_) in 
  self?.updateInitialView() 
} 
self.updateInitialView()
```
