### ISSUE TITLE
Add a button to share the product page URL

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#61]
Add a share icon that will share the product url to your favorite service. The url should change based on the UX language.

https://world.openfoodfacts.org/product/80051428
https://world-fr.openfoodfacts.org/product/80051428
https://world-de.openfoodfacts.org/product/80051428

**Comment by yegorsch** [comment]
I can try to do it. Should not be hard.

**Comment by yegorsch** [comment]
#64

**Comment by aleene** [comment]
Seems we lost this change in the new IOS app?
