### ISSUE TITLE
Clicking on "Analyse des ingredients" does not open ingredient analysis while "Allertes allergies" does

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#616]
Clicking on "Analyse des ingredients" does not open ingredient analysis while "Allertes allergies" does

![image](https://user-images.githubusercontent.com/1689815/75446327-7c4ac580-5967-11ea-98eb-a896050025e4.png)

**Comment by philippeauriach** [comment]
I don't know why but the auto link does not work, PR is ready : #617
