### ISSUE TITLE
Uploaded photos (from edit or add mode) are not selected

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#620]
Uploaded photos (from edit or add mode) are not selected.
The expected result is that they are selected. I'm unsure about what we changed that altered that behaviour.

We got multiple reports from users, and I could reproduce the bug.

**Comment by aleene** [comment]
Is this uploading when there is no image yet? Or replacing existing images?

**Comment by teolemon** [comment]
I could reproduce at least when replacing existing image. I don't have a device right now to test the other case.

**Comment by teolemon** [comment]
@aleene here's an example for a new product:
https://world.openfoodfacts.org/product/33922590204676

**Comment by aleene** [comment]
So there are two cases:
 - No previous image: need some more details. Does it depend on image type (front/ingredients/nutrition)? Or is it always? (I seem to remember that it worked for me). Is it only for new new images? Or is it valid for products that are already there, but have an image added?
 - Previous image: in this case the existing image should be deselected first. I noticed with my app that the deselection does not always work (right away?). Still have to figure out if this is a timing issue (the server did not finish its deselection on time) or whether it is another api issue.

**Comment by aleene** [comment]
As far as I can determine the deselect API is a bit fickle: sometimes it works and sometimes not, It does not seem to be a time-out issue. But now that @stephanegigandet has changed the default behaviour this is no longer very relevant.

**Comment by aleene** [comment]
The upload behaviour seems a bit strange some things are working and somethings not. So a checklist:
Totally new product:
- [ ] front
- [ ] ingredients
- [ ] nutrition

Existing product without images:
- [ ] front
- [ ] ingredients
- [ ] nutrition

Replacing images:
- [ ] front
- [ ] ingredients
- [ ] nutrition

**Comment by aleene** [comment]
We need to implement a refresh on succesful upload.

**Comment by aleene** [comment]
The cropViewController is not presented, so no ingredients images can be created.

**Comment by aleene** [comment]
I am trying to understand how the app works. For images there seem to be two approaches: productAdding and editing. It seems that the editing part is lacking implementations for updating the view after image change/upload.

**Comment by aleene** [comment]
It seems I have solved the refresh issue (with notifications). At least we now see whether an image has been uploaded.
