### ISSUE TITLE
Master no longer works

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#631]
**Summary:** 
![Screenshot 2020-03-14 at 13 34 17](https://user-images.githubusercontent.com/1329905/76682007-91c31f00-65f8-11ea-90f7-661d3d59cf1b.png)
It seems I can no longer login either.

**Comment by aleene** [comment]
The url to request the data is strange:
![Screenshot 2020-03-14 at 13 45 04](https://user-images.githubusercontent.com/1329905/76682170-106c8c00-65fa-11ea-8f70-3e00243517bf.png)

**Comment by aleene** [comment]
This in turn is determined by:
![Screenshot 2020-03-14 at 13 49 52](https://user-images.githubusercontent.com/1329905/76682250-b7e9be80-65fa-11ea-9876-e267ff42ece2.png)

**Comment by aleene** [comment]
So I guess the build is set to testing and not release. So what should be changed? I am not familiar with setting the build settings.

**Comment by aleene** [comment]
```
To create a release build, you have to edit your current scheme (⌘<) and highlight "Run [name of application]. On the right, select "Build Configuration" and choose "Release". Build as usual.
```

**Comment by aleene** [comment]
So why these local endpoints for debugging as it disables a large part of the app?

**Comment by teolemon** [comment]
Can I close this one ?
