### ISSUE TITLE
Xcode changing branches

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#632]
**Summary:** 
I get this when trying to change a branch.
![Screenshot 2020-03-14 at 16 36 02](https://user-images.githubusercontent.com/1329905/76685171-f63ea800-6611-11ea-971c-94fe93edc8b7.png)

There are no changes that need to be committed (checked with `git status`). 

I played around with doing some edits and commits in order to get into a correct status, but that did not work.

**Comment by aleene** [comment]
https://stackoverflow.com/questions/11910228/cannot-push-pull-or-merge-git-working-copy-has-uncommited-changes

**Comment by aleene** [comment]
I can create a new branch and check that one out. And move back again. 

So this new approach for creating the project has borked my old branches.

**Comment by teolemon** [comment]
@aleene is that a bug related to this repo ? Can I close ?

**Comment by aleene** [comment]
Yes let's close it, I guess it has been solved in the mean time.
