### ISSUE TITLE
The login/email wording is not clear enough compared to the website

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#646]
As reported by a user on contact@
```
The mobApp does not seem to accept new contributors!
Login / process behave strange
Even though newly registered on the webapp, with guarantied pass and login name.
Why the Mobapp does not sync with the webapp? Cloud service?
```

**Comment by teolemon** [comment]
@stephanegigandet

**Comment by aleene** [comment]
I do not think I understand this. Mobapp synch with web app?

**Comment by teolemon** [comment]
I think he refers to the official app and the website. Some people make the confusion between the email and the user id. One will let you log in, the other not. I'm not even sure which one.

**Comment by aleene** [comment]
Need to check whether we have to use the email or the user id with the api.

**Comment by aleene** [comment]
So on IOS you can login with both your username or your email address.

So what is the issue?
