### ISSUE TITLE
Image type not set

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#648]
**Summary:** 
When uploading an image for a new product the image type is not set.

**Comment by aleene** [comment]
It seems the imageType as set by the buttons is not passed on.

**Comment by aleene** [comment]
This works, but the language of the image is not set.

**Comment by teolemon** [comment]
Can you give the steps to reproduce ?

**Comment by aleene** [comment]
Create a new product and image.

**Comment by teolemon** [comment]
I don't quite get what the user visible scenario was
