### ISSUE TITLE
Use the new lite API in Search

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#65]
https://world.openfoodfacts.org/cgi/search.pl?search_terms=nutella&search_simple=1&action=process&json=1&fields=product_name,nutrition_grades_tags,quantity,brands

Beware: ensure you pass all the fields necessary to the URL

**Comment by aleene** [comment]
Does this imply that the old api no longer works?

**Comment by teolemon** [comment]
It still works, no breakage. You have just the possibility to get a much lighter result :-)

**Comment by aleene** [comment]
Can be useful to reduce the amount of json decoding needed. Have to see if it impacts my decoders (which I just rewrote).

I could use it to get more search data in one go (instead of a csv) and do some statistics on it.

**Comment by aleene** [comment]
This is done.
