### ISSUE TITLE
Wrong icon for csv share

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#655]
**Summary:** 
The wrong icon for the csv share is used. Should be an arrow that goes up.

**Comment by teolemon** [comment]
that goes down

**Comment by aleene** [comment]
It should go out of the box not into (import).
![File](https://user-images.githubusercontent.com/1329905/82248047-c8dee500-9947-11ea-9589-45391b1d9ce8.jpg)

**Comment by teolemon** [comment]
ah ok

**Comment by aleene** [comment]
At the moment a system icon is used. But I think that is only valid above IOS13

**Comment by aleene** [comment]
The standard action icon can be used.
