### ISSUE TITLE
Issue with translations on photo taking screen

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#659]
![image](https://user-images.githubusercontent.com/1689815/82356978-abbc1c00-9a04-11ea-9996-1fc776ef6a52.png)

**Comment by aleene** [comment]
It is not in our code. A library?

**Comment by aleene** [comment]
https://stackoverflow.com/questions/40859312/ios-10-camera-view-showing-api-cancel-title-instead-of-cancel

**Comment by aleene** [comment]
Seems to be due to the language changer.

**Comment by aleene** [comment]
So I can add some of these, to the english file. For the moment I only do the `cancel` one


"PHOTO" = "PHOTO";
"AEAF_LOCK_TEXT" = "AE/AF LOCK";
"API_CANCEL_TITLE" = "Cancel";
"HDR_AUTO" = "Auto";
"HDR_ON" = "On";
"HDR_OFF" = "Off";
"TIMER_OFF_TEXT" = "Off";
"USE_PHOTO" = "Use Photo";

"PHOTOS" = "Photos";
"CAMERA_ROLL" = "Camera roll";
"ALL_SCREENSHOTS" = "Screenshots";

"CANCEL" = "Cancel";
"RETAKE" = "Retake";
"STREAM_SHARED_BY_ME_SUBTITLE" = "From You";
"STREAM_SHARED_BY_SUBTITLE" = "From %@";
"ALBUM_IMAGE_COUNT_FORMAT" = "%@ Photos";
"ALBUM_VIDEO_COUNT_FORMAT" = "%@ Videos";
"1_ALBUM_PHOTO" = "1 Photo";
"1_ALBUM_VIDEO" = "1 Video";
"ALBUM_TWO_TYPES_LABEL_COMMAS" = "%@, %@";

"ALL_PHOTOS_IN_LIBRARY" = "Moments";
"PXUserCollectionsSectionTitle" = "My Albums";
"FULL_PHOTOS_GRID_ZOOM_LEVEL_TITLE" = "Moments";
"NO_PHOTOS_OR_VIDEOS" = "No Photos or Videos";
"EMPTY_ALBUM_LIST_MESSAGE_iPhone" = "You can take photos and videos using camera, or sync photos and videos onto your iPhone using iTunes";

**Comment by teolemon** [comment]
"PHOTO" = "PHOTO";
"AEAF_LOCK_TEXT" = "AE/AF LOCK";
"API_CANCEL_TITLE" = "Cancel";
"HDR_AUTO" = "Auto";
"HDR_ON" = "On";
"HDR_OFF" = "Off";
"TIMER_OFF_TEXT" = "Off";
"USE_PHOTO" = "Use Photo";
"PHOTOS" = "Photos";
"CANCEL" = "Cancel";
"RETAKE" = "Retake";

**Comment by teolemon** [comment]
how about this ?

**Comment by aleene** [comment]
If we are usung those. I can not check it with my device.

**Comment by teolemon** [comment]
Still here
![image](https://user-images.githubusercontent.com/1689815/92887333-b1ef6180-f414-11ea-8a8b-a8abf83f63a9.png)
![image](https://user-images.githubusercontent.com/1689815/92887374-b9166f80-f414-11ea-906d-0c3ea797841d.png)

**Comment by aleene** [comment]
Same as #683

**Comment by aleene** [comment]
I'll add some more strings.
