### ISSUE TITLE
Use the new lite API in the Quick Scan mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#66]
https://world.openfoodfacts.org/cgi/search.pl?search_terms=nutella&search_simple=1&action=process&json=1&fields=product_name,nutrition_grades_tags

Beware: ensure you pass all the fields necessary to the URL

**Comment by aleene** [comment]
In class `Productservice` the following url is used at the moment:

`url += "/cgi/search.pl?search_terms=\(encodeParameters(query))&search_simple=1&action=process&json=1&page=\(page)"`

Any idea to which fields we should limit the search query?

**Comment by aleene** [comment]
The fields are used in another query, so I just copy those.
