### ISSUE TITLE
Add support for editing the energy both in kcal and kj 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#675]
Add support for editing the energy both in kcal and kj.
Please check the ongoing discussions in #api

**Comment by aleene** [comment]
This means that a new field must be added in edit/add mode.

**Comment by aleene** [comment]
Needed changes:

- OFFReadAPIkeysJSON, need to add two keys, one for kJ and one for kcal.

**Comment by aleene** [comment]
There is an array with literal strings, which displays the default nutrients (displayedNutrimentItemsByDefault). Turns out this is not translated.
