### ISSUE TITLE
Clipped text in settings (English)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#685]
![image](https://user-images.githubusercontent.com/1689815/84591150-76a4bd00-ae3c-11ea-9f6a-5d03d4c03745.png)

**Comment by aleene** [comment]
OK, move to two lines.

**Comment by aleene** [comment]
Or decrease the length of the translation to `Products pending upload`.

**Comment by SwipeInteractive** [comment]
Hi, 

I'm new to the project. This looks like a good issue to pick up to get used to creating a PR. Can I pick it up?

Thanks, 
Vick

**Comment by aleene** [comment]
I think we will just reduce the length of the translation. A two-line button is not so nice.

**Comment by vicksolanki** [comment]
Yeah I agree it doesn't look great. The screenshot below is simply by changing the wrap behaviour of the button but I think shorter text is better. However will this be dependant on getting new translations? 

![IMG_5669](https://user-images.githubusercontent.com/6295072/86114700-d1881680-bac2-11ea-80af-037c0ad0dde0.PNG)

**Comment by aleene** [comment]
Checkout the `.localized`. Add the english text in front, and add the new english text to the english localized filed (in the folder Localisations).

**Comment by vicksolanki** [comment]
Ah yes I can change a single value for English but the length looks long for multiple languages. They should all be changed in sync no? If not, I can go ahead and make the change.

**Comment by philippeauriach** [comment]
IMO we should do both : allow the button to go on two lines if needed (even if it is not beautiful, it is better than a truncated text) AND change the translation in the languages we master. The problem with just changing one translation is that it does not fix the issue for other languages, especially long ones (such as german for example, it is always longer than english). If possible (I do not master our translation system enough), we should indicates as a comment

**Comment by vicksolanki** [comment]
Ok, I can create a small PR to fix the truncation in the short term and then raise another issue for changing the translation? As it's better to be consistent across all the languages?
