### ISSUE TITLE
[Proposal] New labels experience (from links to images)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#707]
[Proposal] New labels experience (from links to images)
![image](https://user-images.githubusercontent.com/1689815/89712899-25283280-d994-11ea-815f-5104dab145cd.png)
https://docs.google.com/document/d/1ADRNzOZGRS308Ve02tHbSLnaksw3_tdSyXtIB9kIGz0/edit#heading=h.rn7so1lxwbej

**Comment by teolemon** [comment]
We should probably do a mockup with one label in a branch, and make it generic when we stabilize an API

**Comment by aleene** [comment]
See the module TagListView.

**Comment by teolemon** [comment]
I'm adding the latest mockup @jncosideout 
![image](https://user-images.githubusercontent.com/1689815/96977628-a2882b80-151d-11eb-8728-3f7f256a90d8.png)

**Comment by jncosideout** [comment]
Thanks. I will work toward that as close as I can. Will you please tell me the difference between the two since they look almost identical to me.
