### ISSUE TITLE
Missing energy-kcal key in translations

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#716]
- [ ] Missing energy-kcal key in translations

![image](https://user-images.githubusercontent.com/1689815/90133305-845cbd00-dd6f-11ea-8398-6a96991f0002.png)

**Comment by aleene** [comment]
The translations should be added to the Nutriments taxonomy.

**Comment by aleene** [comment]
We can implement an exception as a stopgap.

**Comment by jncosideout** [comment]
I am trying to replicate this error on my device and found something odd. 
None of the Nutriments, including 'energy-kcal,' are translated for me.
Despite the following combinations of Phone language && app language:
e.g. phone = English && app = Français | phone = Français && app = Français
 
Is there some configuration I'm missing? I tested it on the 'develop' branch.
![ingredients-tab-app-Francais](https://user-images.githubusercontent.com/25991237/95028482-14c7c780-0666-11eb-9411-5514a10c0d09.png)

[EDIT]
After debugging, I've found that each Nutriment that is retrieved from DataManager has an empty `names` list
Here is a sample debug output printed:

    Optional<Nutriment>
      some : Nutriment {
        code = saturated-fat;
        names = List<Tag> <0x28bd134e0> (
            
        );
        mainName = ;
        indexedNames = ;
     }

Also, and maybe you are already aware, 'energy-kcal' never gets retrieved from DataManager. 

I tried running the app with all Taxonomies downloaded (which only seems to be possible on my branch for #720 'Add-Labels-to-Taxonomies-Service') to make sure that translations could be sourced from them, but as you can see above, the Nutriments still have empty `names` lists, which means they can't be translated via TagTransform.swift.

I still don't know why it shows translated Nutriments (**except energy-kcal**) for you and not me though.

**Comment by aleene** [comment]
Did you use the version of the app you repaired? Or develop?

**Comment by aleene** [comment]
![image](https://user-images.githubusercontent.com/1329905/95048809-d0314000-06e8-11eb-9bf6-f0861a1892d3.png)

Ipad is on dutch.

**Comment by aleene** [comment]
Still need to account for the language setting in the app.
