### ISSUE TITLE
Replace "Delete" by a bin icon in history to save space.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#724]
![history-ios](https://user-images.githubusercontent.com/1689815/91226981-11b3f000-e726-11ea-8d37-627e7ade20de.png)

**Comment by twink1e** [comment]
hello! just replacing the text with the system default icon https://developer.apple.com/documentation/uikit/uibarbuttonitem/systemitem/trash right?

would like to take this task :)
