### ISSUE TITLE
Fix toggle behaviour when setting is too long

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#725]
Fix toggle behaviour when setting is too long. The toggle should be on top. People will guess the end of the word.
![image](https://user-images.githubusercontent.com/1689815/91227283-8d15a180-e726-11ea-965e-e8d8d77659f6.png)

**Comment by aleene** [comment]
In this case we might adapt the translations as well:

- Affichages des Analyses
- Statut Huile de Palme

**Comment by aleene** [comment]
![image](https://user-images.githubusercontent.com/1329905/95602617-71a3f300-0a55-11eb-952d-d43b69120142.png)
