### ISSUE TITLE
Search spins forever when there are no results

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#726]
![image](https://user-images.githubusercontent.com/1689815/91228455-9273eb80-e728-11ea-9725-7e8dcd2f92e2.png)

**Comment by aleene** [comment]
I guess the refresh control spinner is not stopped, when there are no results

**Comment by aleene** [comment]
The spinner is started as soon as the user types in a character. This is too soon, it should happen only after the search has started (tapping Search).

It is already set to `.loading` in `updateSearchResults(for searchController:)`, which is not even used in production.

**Comment by aleene** [comment]
PS the keyboard return button should indicate **Search**.
