### ISSUE TITLE
Hide "City and country of purchase"

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#727]
Hide "City and country of purchase". This does not bring any value to the user: 

- the field is returned as a slug
- we have the value 5% of the time.
- What's the point knowing that someone bought it in Lyons, France, when I'm in Paris France.

The only interesting field is "Countries" which is already shown below.

![image](https://user-images.githubusercontent.com/1689815/91229258-d61b2500-e729-11ea-90e2-fff13985ad11.png)

**Comment by tejuamirthi** [comment]
Hey @teolemon  I'd like to take up this issue

**Comment by teolemon** [comment]
Welcome @tejuamirthi :-) you can go ahead
