### ISSUE TITLE
Unrecognized Locale - ber, me, ry, son, tzl

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#736]
ITMS-90176: Unrecognized Locale - - The locale names used in localization directories at ( 'Payload/OpenFoodFacts.app/ber.lproj', 'Payload/OpenFoodFacts.app/me.lproj', 'Payload/OpenFoodFacts.app/ry.lproj', 'Payload/OpenFoodFacts.app/son.lproj', 'Payload/OpenFoodFacts.app/tzl.lproj' ) are invalid. iTunes supports BCP47 but not the UN M.49 specification. Refer to the Language and Locale Designations guide at https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html for more information on naming your language-specific directories.

**Comment by aleene** [comment]
See #634

**Comment by aleene** [comment]
https://en.wikipedia.org/wiki/IETF_language_tag#ISO_639-3_and_ISO_639-1

https://tools.ietf.org/html/bcp47

* ber - berber - ISO 639.2 is ber
* ry - rusyn - has no ISO 639.2 equivalent
* tzl - talossan - has no ISO 639.2 equivalent

**Comment by aleene** [comment]
My proposition is to remove these languages from the localizations and from crowdin.

**Comment by teolemon** [comment]
fixed
