### ISSUE TITLE
display edit button on the bottom card (if brand & name & nutriscore & nova are all empty)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#737]
display edit button on the bottom card (if brand & name & nutriscore & nova are all empty)

![image](https://user-images.githubusercontent.com/1689815/95012195-c5b66e00-0636-11eb-98ae-a76945f8b21d.png)

Add a hint that you can slide-up the card for more details. This is especially useful when it is empty.
```
if brand && name && nutriscore && nova is empty: display edit button
if nutriscore && nova is empty && misc =! nova-not-applicable && misc=! nutriscore-not-applicable: display edit button
```

**Comment by aleene** [comment]
The corresponding action occurs in `class ScanProductSummaryView`. If there is no data the fields will not be filled.

**Comment by aleene** [comment]
![image](https://user-images.githubusercontent.com/1329905/95110798-dd791980-073e-11eb-9966-0be1d2f5f77b.png)
