### ISSUE TITLE
Bad layout for the NOVA prompt (plus not actionable)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#738]
Bad layout for the NOVA prompt (plus not actionable, should be a button bringing to OCR)
![image](https://user-images.githubusercontent.com/1689815/92961791-2efbf480-f470-11ea-8fc5-5012020835e9.png)

**Comment by aleene** [comment]
This is caused by the missing NOVA image. Can I add a minimum width?

**Comment by teolemon** [comment]
That's a solution. Also turning it into a button that jumps into editing if states= `ingredients-to-be-completed` ?

**Comment by aleene** [comment]
It was a retorical question, to see if this solution would work.

**Comment by aleene** [comment]
I am no a fan of buttons all over the place. There is still a pull request to put the edit button op top. We could change the state of this button if editing is required.

**Comment by teolemon** [comment]
Buttons are a direction towards what the user want: the scores. They are a necessary evil.

**Comment by aleene** [comment]
On the position of the nova icon, we can put a button.
