### ISSUE TITLE
TabBar icon texts is half translated in French

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#739]
![image](https://user-images.githubusercontent.com/1689815/92961886-581c8500-f470-11ea-9c93-aa0815c3e693.png)

**Comment by aleene** [comment]
These are written in the Storyboard as User Defined Runtime Attributes, but also as System Items, so the system should do the translations. It seems these titles can not be stranslated.

So we need to make them all Custom and assign the standard icons.
