### ISSUE TITLE
Missing strings in the camera

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#740]
Probably because the strings haven't been added to the proper files
![image](https://user-images.githubusercontent.com/1689815/92962093-b5183b00-f470-11ea-9e16-3f0c61af02e7.png)
![image](https://user-images.githubusercontent.com/1689815/92962099-b8132b80-f470-11ea-9c2b-7c8acf3545bf.png)

**Comment by damien-rivet** [comment]
Hi @teolemon,

I would like to work on this issue, should be a small PR.

Thanks.

**Comment by teolemon** [comment]
Bonjour @Ethenyl :-) 
I'm checking with @aleene that it's still open, and after that you're good to go.

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-ios/issues/659

**Comment by teolemon** [comment]
@Ethenyl it's good 👍

**Comment by aleene** [comment]
Just add the lines in #659 to the english localization file

**Comment by damien-rivet** [comment]
Ok, I will start working on it as soon as possible. Thanks for the heads up.

**Comment by damien-rivet** [comment]
Fixed in #735.
