### ISSUE TITLE
Links to OFF.org do not update when Language is changed

### ISSUE THREAD

**Issue by jncosideout** [openfoodfacts/openfoodfacts-ios#746]
**Checklist**
- [x] Bug Report 
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:** 

When tapping on a Category or taxonomy in the product details section, or when tapping an Ingredient Analysis Icon and choosing "Help translate ingredients," the app opens a webpage to world-(user's language).openfoodfacts.org
The subdomain of OFF.org should change when the user changes the language in the app but instead it always points to the language of the device's preferred localization in the device's Settings.

**Steps to reproduce:** 

 - choose a language in the OFF language settings that is different from the device's main language
 -  scan a product
 -  tap on a hyperlink to a category to view the description on off.org
 OR
 - tap on a grey Ingredient Analysis icon (e.g. the palm oil monkey) and tap the blue button that says "Help translate the ingredients in your language" then another blue button that says "Help translate ingredients"
 - a webview will pop up in the app that brings you to world-(your-chosen-language).openfoodfacts.org

**Expected behavior:** 

Open a webpage to openfoodfacts.org for the language chosen in the app

**Observed behavior:** 

A webpage opens to openfoodfacts.org for the default language of the device, regardless of the chosen language in the app.

**Device and iOS version:** 

Apple iPhone 6 running iOS 12.3.1
**Screenshots:** 

1. Device settings in English
![Device-lang](https://user-images.githubusercontent.com/25991237/94374081-6c4abe00-00cf-11eb-9bb7-5095e77139e2.png)
2. Change OFF app lang to Français
![OFF-app-lang-1](https://user-images.githubusercontent.com/25991237/94374265-a9fc1680-00d0-11eb-8cc1-2497b573ac23.png)
3. After scanning a product which has no palm oil info, tap to "Help translate ingredients"
![ingredients-help-translate](https://user-images.githubusercontent.com/25991237/94374280-bed8aa00-00d0-11eb-90fa-90f8a29ba7b5.png)
4. The webpage opens to https://world-**en**.openfoodfacts.org/ingredients?translate=1, but it should point to "https://world-**fr**.openfoodfacts.org/ingredients?translate=1
![world-en openFF org](https://user-images.githubusercontent.com/25991237/94374283-c6984e80-00d0-11eb-8fbd-05316c6d52ef.png)

\* Note that this bug can also be replicated through the links on the product taxonomies, e.g. Categories: Snacks has a hyper link to https://world.openfoodfacts.org/category/snacks and it has the same language problem.

**Comment by aleene** [comment]
Try https://fr.openfoodfacts.org/category/snacks, you'll see there are a lot less products.

**Comment by aleene** [comment]
So it should point to https://world-fr.openfoodfacts.org/category/snacks

**Comment by jncosideout** [comment]
> So it should point to https://world-fr.openfoodfacts.org/category/snacks

It does. In PR #747 the changes addressed the language prefix after "world-" in the url. So "world-" has not been removed.

**Comment by aleene** [comment]
Sounds good then.
