### ISSUE TITLE
Add a button on the product page to take a picture of the recycling instructions

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#749]
Add a button on the product page to take a picture of the recycling instructions and upload it to the server.
This can be achieved using the "Take another picture" code.
This is very important for the Environnemental Scoring project.

**Comment by aleene** [comment]
Is it already supported on the server?

**Comment by teolemon** [comment]
@aleene on-going work. Meanwhile, we can upload without selecting it. 
Server-side issue: https://github.com/openfoodfacts/openfoodfacts-server/issues/4286

**Comment by aleene** [comment]
I did not check the jsons, but is it already calculated and published. Then this one can be started.

**Comment by aleene** [comment]
We need to know the code to send in the image api.

**Comment by aleene** [comment]
> In addition to "front", "ingredients" and "nutrition", we can add a new "packaging" image type, to hold either packaging info / logos, or if available recycling instructions. (if both are available, they are often close)

**Comment by teolemon** [comment]
We have a better documentation on the Android issue. It behaves exactly like the ingredients image field 
- https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3531

**Comment by teolemon** [comment]
fixed by @aleene
