### ISSUE TITLE
Add a link to the ingredient analysis section of settings

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#763]
Add a link to the ingredient analysis section of settings
We plan on adding many more analysis, so we need a scalable way to enable and disable them
(Also sorry for the mockup copy paste from Android)
![image](https://user-images.githubusercontent.com/1689815/95025494-5ec2a480-068a-11eb-9281-d34e897e0400.png)

**Comment by aleene** [comment]
Not really a fan of adding a button here, but I'll have a go at it.

**Comment by aleene** [comment]
The ingredient analysis icons are added to a stackView during runtime. We could add an extra button as well.

**Comment by aleene** [comment]
![image](https://user-images.githubusercontent.com/1329905/95478287-a2b6f180-0989-11eb-806d-ab147571b9fc.jpeg)

**Comment by teolemon** [comment]
great, it would be good to bring it in visual coherence with the other ones. I put it on the extreme right so that no confusion could be done between it and the actual analysis. 
Potentially, the analysis icons could be subducted (go below it) if they overflow, with the ability to drag left to see the overflowing ingredient analysis icons (assuming someone decides to enable the 12 allergens + gluten, vegan…

**Comment by aleene** [comment]
The extreme right is not nice. It looks detached and the relation with the allergens is unclear.

For visual coherence I decided for a filled Icon. Blue to indicate it is a button (standard iOS). Round to distinguish is from the icons and from the standard product edit button. I think I will make it a bit larger though.

Overflow etc will not work at the moment. Requires a totally different implementation for presentation.
