### ISSUE TITLE
The Environment tab HTML should go dark mode like the nutrition table HTML

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#765]
The Environment tab HTML should go dark mode like the nutrition table HTML. We should also take the advantage to use the system font like we do for nutrition.
![IMG_0078](https://user-images.githubusercontent.com/1689815/95183898-ead9e680-07c6-11eb-94a1-b7382d95cb52.PNG)
![IMG_0079](https://user-images.githubusercontent.com/1689815/95183909-ec0b1380-07c6-11eb-873e-98b42173d82c.PNG)

**Comment by aleene** [comment]
Why can't we go native right away and need to use html?

**Comment by teolemon** [comment]
Products attributes will do that. Meanwhile, we need to display Eco-Score disclaimers, explanations in a flexible way, without having to code and ship a new version with every fix or translation.

**Comment by teolemon** [comment]
fixed by @aleene
