### ISSUE TITLE
Travis build seem to be stuck

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#772]
Travis build seem to be stuck for some reason

**Comment by mike011** [comment]
Yeah looking at https://travis-ci.org/github/openfoodfacts/openfoodfacts-ios/requests it is failing with: "Build config did not create any jobs." which seems to indicate the build is not configured correctly. Looking at the history of the yaml config file the last change makes it fail. https://github.com/openfoodfacts/openfoodfacts-ios/commit/4f7b2da90cdb49709db79e81b7f0610b37d1888d  So the easiest thing would be to refer that behaviour and reevaluate how to add Testflight support. Thougts?

**Comment by mike011** [comment]
@teolemon ??

**Comment by teolemon** [comment]
mmh @philippeauriach on this one ?

**Comment by philippeauriach** [comment]
Yep ! The job linked above in the yml configuration is the following : 
```jobs:
  include:
    - stage: Deploy
      name: Deploy to TestFlight
      script:        
        - bundle exec fastlane beta
      if: branch =~ /^release\/.*$/
```
It is meant to deploy the app on testflight, only on a `release/*` branch, and therefore, it is normal that no job is launched when pushing on develop or on any other branch different from `release/*`. This is on purpose, we don't want to release a beta version of the app on every push on develop or other branches. 

Last build on release did trigger the job correctly: https://travis-ci.org/github/openfoodfacts/openfoodfacts-ios/branches

Travis indicating "Build config did not create any jobs." is not an error, just an information that there is nothing to be done.

Aside of this, if you have suggestions for jobs that should be ran for develop and other branches, feel free to make suggestions (but keep in mind that we have plan to switch to github action from travis, as we did for android).

**Comment by teolemon** [comment]
I've made an initial PR to move it to GitHub actions
