### ISSUE TITLE
Allow to add labels and certifications when adding a new product

### ISSUE THREAD

**Issue by Jiehong** [openfoodfacts/openfoodfacts-ios#775]
**Checklist**
- [x] bug report: did not find another issue related to that (well, https://github.com/openfoodfacts/openfoodfacts-ios/issues/190 seems to talk about it, but it didn't happen)
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software: unable to.

**Summary:** 

Currently, it is only possible to add labels (such as "Bio" or "Vegetarian") on the website, but not via the app itself.

A new "labels, certifications and awards" field should be added, to follow what the website allows.

**Device and iOS version:** 

Apple iPhone 8+ running iOS 14.0.1 (app version: 3.3)

**Comment by aleene** [comment]
It is already displayed on the summary tab, so this is only for editing. Let's add it below language for the moment.

**Comment by teolemon** [comment]
This is mostly fixed by @aleene
