### ISSUE TITLE
$(PRODUCT_NAME) does not need to be translatable

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#78]
$(PRODUCT_NAME) does not need to be translatable

**Comment by snuff4** [comment]
@teolemon In the InfoPlist.strings, there is `"CFBundleName" = "$(PRODUCT_NAME)";`
I found that 

> CFBundleName is what gets displayed in the menu bar and the application’s Info window.

So can we name $(PRODUCT_NAME) as Open Nutrition?
