### ISSUE TITLE
Increase usability of general fields in editing mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#785]
### Rationale
- The name of the fields is often clipped
- The values of the fields is often clipped

#### Core
(This is already the case for nutrition fields)
- [ ] Make the fields edge to edge to increase legibility, usability and avoid clipped text 
- [ ] Put the field name above it

#### Nice to have
- [ ] Increase the height of the field if the text overflows

![image](https://user-images.githubusercontent.com/1689815/98096834-7f9a3780-1e8c-11eb-94d8-e724cc2de535.png)

**Comment by hfehrmann** [comment]
Hi!
I would like to give it a try.

**Comment by teolemon** [comment]
Welcome @hfehrmann :-) I've just assigned you. You can also join the discussion on Slack : https://slack.openfoodfacts.org
