### ISSUE TITLE
String confusing translators

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#79]
![image](https://user-images.githubusercontent.com/1689815/37403658-dd060828-278f-11e8-9b15-9f769d4b57ac.png)

Those strings are confusing translators. They should either be clarified or made untranslatable.

**Comment by snuff4** [comment]
These strings are under OpenFoodFactsTests. We can add Source and Target the same way done in the normal Localizable.strings.

Working on it.

**Comment by snuff4** [comment]
Is translating strings for Test needed? 
If no, we can delete them.
If yes, we can translate it the same way as normal Localizable.strings, but there will be repetition of some strings.

What do you say @teolemon ?
