### ISSUE TITLE
Remove the condition to display the Environment tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#790]
Remove the condition to display the Environment tab, since we're going to always display it (to collect photos of recycling instructions, and add explanations in the existing HTML insert)

**Comment by hfehrmann** [comment]
@teolemon Can you clarify this issue? I do not understand the desire.

**Comment by aleene** [comment]
In `productDetailViewController` we have:
```
fileprivate func getEnvironmentImpactVC() -> UIViewController? {
        if product.environmentImpactLevelTags?.isEmpty == false, let infoCard = product.environmentInfoCard, infoCard.isEmpty == false {
            let environmentImpactFormTableVC = EnvironmentImpactTableFormTableViewController()
            environmentImpactFormTableVC.product = product
            return environmentImpactFormTableVC
        }
        return nil
    }
```

I guess we can remove the check, so that it is always shown.
