### ISSUE TITLE
ecoScore on environment tab

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#797]
**Summary:** 
Goal to show the ecoScore on the environment app, and add it to the assets.

**Comment by aleene** [comment]
Is there an image for ecoScore unknown/uncalculable?

**Comment by teolemon** [comment]
There is: https://github.com/openfoodfacts/openfoodfacts-ios/issues/744

**Comment by aleene** [comment]
Looks like I will incorporate the packaging image as well in this issue. I try to copy as much code as possible from the ingredients tab.
Later we have to incorporate the stuff from the old environments tab.

**Comment by teolemon** [comment]
looks good 👍

**Comment by aleene** [comment]
The implementation I go now implements:
- added ecoscore assets
- display of ecoscore on environment tab
- display of packaging image on environment tab
- display of packaging field on environment tab

Next step is to link with the json.

**Comment by aleene** [comment]
What are the ecoscore related fields in the json:
- "ecoscore_score":77.3330654516856
- "ecoscore_tags":["b"]
- "ecoscore_data":{"agribalyse":{"agribalyse_food_name_en":"Crispbread, extruded and grilled","agribalyse_ef_total":"0.19327557","agribalyse_proxy_food_code":"7410","score":84.2080654516856,"agribalyse_food_name_fr":"Tartine craquante, extrudée et grillée"},"status":"known","grade":"b","adjustments":{"production_system":{},"packaging":{"value":-1.875,"score":81.25,"packagings":[{"ecoscore_counted":1,"ecoscore_material_score":"0","shape":"en:film","ecoscore_shape_ratio":"0.1","recycling":"en:discard","material":"en:plastic"},{"ecoscore_shape_ratio":"1","recycling":"en:recycle","shape":"en:box","material":"en:cardboard","ecoscore_material_score":"91.25","ecoscore_counted":1}]}
- "ecoscore_grade":"b"

For our purposes the `ecoscore_grade` is enough.

**Comment by teolemon** [comment]
Yes it is. The rest is for debug purposes.

**Comment by aleene** [comment]
The upload of the packaging inage does not work well. It is uploaded as a packaging image, but under language `xx`.

**Comment by teolemon** [comment]
They are language dependent, so you can pass the current language.

**Comment by aleene** [comment]
Yes I know. It was just to record a remaining bug.

**Comment by aleene** [comment]
![image](https://user-images.githubusercontent.com/1329905/100099244-76830180-2e5f-11eb-8fbe-9bfa5f4dbfaf.jpeg)

**Comment by aleene** [comment]
Wonder how and when to decide to refresh the offline products with `refreshOfflineProductsFromServerIfNeeded()`.

Now the data is refreshed after one month. We could add a specific data: if the last download is older than that data, do a refresh.
