### ISSUE TITLE
Missing string

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#807]
![image](https://user-images.githubusercontent.com/1689815/100773234-e1ed4600-3400-11eb-8e78-f01e0e3920e1.png)

**Comment by aleene** [comment]
These should be filled in through Crowdin?

**Comment by teolemon** [comment]
It seems to be missing from the source string file:
https://github.com/openfoodfacts/openfoodfacts-ios/search?l=Swift&q=call-to-action.environment

**Comment by aleene** [comment]
The complete line is:
`                callToActionView.textLabel.text = "call-to-action.environment".localized
`
So I do not know why you could not find it.

I also added to the the english localisation file, but that did not help. Maybe crowdin picks it up now?
