### ISSUE TITLE
The language prefixes are visible in the Labels field for untaxonomized values

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#819]
The language prefixes are visible in the Labels and Packaging fields for untaxonomized values. 
The field should behave like the server:

- [ ] Untaxonomized values in Italic if it's in the same language as the UI
- [ ] Keep the language prefix if it's different than the UI

**Comment by aleene** [comment]
Requires the same solution as #806

**Comment by aleene** [comment]
See also #808

**Comment by aleene** [comment]
Probably the label and packaging fields are the only mixed language fields.

**Comment by aleene** [comment]
How does this behave for categories?
