### ISSUE TITLE
Disable ecoscore

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#822]
**Summary:** 
Disable the ecoscore, so a version can be shipped, which allows taking packaging photo's

**Comment by aleene** [comment]
We can suppress the reading of the alpha field. This will not show the calculated ecoscore, but will leave the images, etc.

**Comment by teolemon** [comment]
Yes, just the alpha. That means that all users will be launch ready with the non-final logo. We'll ship an additional update with the finalized logos.

**Comment by aleene** [comment]
You might get questions on what that grey ecoscore logo is doing there.
