### ISSUE TITLE
Add examples in edit mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#837]
Add examples in edit mode

- [ ] Labels
- [ ] Packaging
- [ ] Brand

**Comment by aleene** [comment]
I guess you mean placeholders?

**Comment by teolemon** [comment]
On Android we have both a placeholder and an example below. 
Labels as a placeholder, and value exemple below the field.

**Comment by aleene** [comment]
Can you post an example?

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/102104419-7490da80-3e2e-11eb-9cc4-3d287117354a.png)

**Comment by aleene** [comment]
OK. Are there already standard texts for these?

**Comment by teolemon** [comment]
I more or less used the one from the web
```
<string name="hint_quantity">Examples: 2 l, 250 g, 1 kg, 25 cl, 6 fl oz, 1 pound</string>
<string name="hint_packaging">Examples: plastic, paper, glass</string>
<string name="brand_hint">Examples: Coca-Cola, Nestle, etc…</string>
<string name="hint_emb_codes">Examples: EMB 53062, FR 62.448.034 CE, 84 R 20, 33 RECOLTANT 522, FSSL 10013011001409</string>
```

**Comment by teolemon** [comment]
I realize that the hint for labels is missing on the Android version.
