### ISSUE TITLE
Add support for vitamins and minerals in products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#84]
We recently added support for vitamins and minerals in products.
In some cases, you will find what is below in a product:
```
Added vitamins:
Minerals:
Added amino acids:
Other nutritional substances added:
```

===== Vitamins and minerals detection =====

====== Vitamins ======
<pre>"vitamins_tags":["en:vitamin-a","en:cholecalciferol","en:vitamin-e","en:vitamin-c","en:thiamin","en:riboflavin","en:niacin","en:vitamin-b6","en:folic-acid","en:vitamin-b12","en:biotin","en:phylloquinone"]</pre>
====== Minerals ======
<pre>"minerals_tags":["en:calcium-citrate","en:potassium-citrate","en:sodium-citrate","en:magnesium-chloride","en:calcium-phosphate","en:potassium-phosphate","en:ferrous-sulphate","en:zinc-sulphate","en:cupric-sulphate","en:manganese-sulphate","en:sodium-carbonate","en:potassium-iodide"]</pre>

====== Amino acids ======
<pre>"amino_acids_tags":["en:l-tryptophan"]</pre>

====== Other nutritional substances =====
<pre>"other_nutritional_substances_tags":["en:taurine","en:inositol","en:choline-citrate","en:taurine","en:inositol","en:choline-citrate","en:taurine","en:inositol","en:choline-citrate"]<pre>

**Comment by aleene** [comment]
What does this mean? 
- has these been added to the nutrients taxonomy?
- have this been added as nutrients in the read api?
- are these available in the updare api?
- why are the specified as _tags?

**Comment by teolemon** [comment]
- Those are new ingredient-based taxonomies (Vitamins, Minerals, Amino Acids, Others), and thus specified as tags since they are taxonomized
- Those are separate from nutrients, and detected from ingredients, just like additives or palm oil would

**Comment by teolemon** [comment]
Global vitamins taxonomy
Global minerals taxonomy
Global amino acids taxonomy
Global nucleotides taxonomy
Global other nutritional substances taxonomy

https://en.wiki.openfoodfacts.org/Global_taxonomies

**Comment by aleene** [comment]
I do not understand what the interest is. How would I use this?

**Comment by aleene** [comment]
Is implemented.
