### ISSUE TITLE
The nutrition table appears for products without nutrition

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#849]
The nutrition table appears for products without nutrition. We should hide the table and the take a photo button, and instead put:
"This product does not have any nutrition information on the packaging. If this is an error, please correct it by editing the product"

**Comment by aleene** [comment]
It seems that products without a nutrition table, have the state `en:nutrition-facts-completed`.

We need to check the variable noNutritionData. If there is no nutrition data, the string has the value `on`.

**Comment by aleene** [comment]
Note that in this case there is already a call to action.
