### ISSUE TITLE
Add a mention below the origin ingredients field mentioning it is required for the Eco-Score (in the Edit mode)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#857]
Add a mention below the origin ingredients field mentioning it is required for the Eco-Score (in the Edit mode)

**Comment by aleene** [comment]
We do not show the origin field yet. Need to add it to the ProductAddViewController.

Is this field read from the json? Yes.
Is it displayed? Yes on the SummaryForm, we can move it to the ingredientsForm.
