### ISSUE TITLE
Modify app icon with white background

### ISSUE THREAD

**Issue by rudrankriyam** [openfoodfacts/openfoodfacts-ios#88]
App icon with white background will blend with the UI of the application.

Comparison -
![simulator screen shot - iphone x - 2018-03-31 at 23 54 41_iphonexspacegrey_portrait](https://user-images.githubusercontent.com/30552772/38166564-608d5b72-3543-11e8-96f3-d7da27610705.png)

![icon-1024](https://user-images.githubusercontent.com/30552772/38166568-7d0ea120-3543-11e8-85c7-c9a6b8ab29f9.png)

What do you think @teolemon @roger-tan ?

**Comment by snuff4** [comment]
Nice, I will start working on it.

**Comment by roger-tan** [comment]
My preference will be for the first one.
