### ISSUE TITLE
Identifier Name Violation Issues and Warning after updating to Xcode 9.3

### ISSUE THREAD

**Issue by snuff4** [openfoodfacts/openfoodfacts-ios#92]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker.](https://github.com/openfoodfacts/openfoodfacts-ios/issues)
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:** 

Identifier Name Violation Issues and Warning after updating to Xcode 9.3

**Steps to reproduce:** 

Please provide detailed steps for reproducing the issue.

 - Update to Xcode 9.3
 -  
 -  

**Expected behavior:** 

No Errors
**Observed behavior:** 

18 Warnings and 9 Errors
**Device and iOS version:** 

Apple iPhone [7] running iOS [11.3]

**Screenshots:** 

![screen shot 2018-04-27 at 10 52 12 pm](https://user-images.githubusercontent.com/30552772/39375956-a6ef994c-4a6d-11e8-96b1-256b56ef5eaf.png)

**Comment by roger-tan** [comment]
Probably the next PR to fix!
