### ISSUE TITLE
SwiftLint warnings after first build

### ISSUE THREAD

**Issue by SpacyRicochet** [openfoodfacts/openfoodfacts-ios#929]
After installing SwiftLint, running the project gives quite some warnings, which I presume are due to new SwiftLint defaults. Instead of randomly fixing these, this issue is to determine which rules should be followed and which should be ignored.

The rules that SwiftLint is warning about;

* `comment_spacing`: Generates a lot of warnings, due to commented out code (e.g. `//returnValue += ...`). Considering the prevalence of the commented out code, I'm considering to ignore this rule.
* `file_length`: Especially the `xManagers` classes are quite large. In my experience, we could safely set the relevant files to ignore the rule, since it's often useful to keep the code of such classes together.
* `type_body_length`: Basically the same as for `file_length`. The large files have large bodies, so we could ignore this one in the relevant files.
* `cyclomatic_complexity`: This pops up with files that have a lot of `if/else` statements (e.g. `-PersistanceManager.addPendingUploadItem(_: withNutritionTable:)`. Considering the types of functions it warns for, it might be good to ignore this rule for the current violations, but keep it for future ones.
* `for_where`: Some spots where it suggests using `for where` instead of an `if` inside of a `for`. This one I'd fix.
* `identifier_name`: Some identifier names are too long. I'd suggest ignoring those for now.
* `trailing_whitespace`: There's an option to ignore empty lines. I'd enable this.
* `redundant_optional_initialization`: This can easily be fixed.

_Context; I'm exploring the app to see if there's an interesting accessibility issue that I can solve for Hacktoberfest._

**Comment by teolemon** [comment]
thanks @SpacyRicochet :-)
feel free to open a11y issues as you spot them, we're novices on this area
