### ISSUE TITLE
[a11y] After navigating to Scanner, no headings are available for quick navigation of the screen

### ISSUE THREAD

**Issue by SpacyRicochet** [openfoodfacts/openfoodfacts-ios#937]
When activating the Scanner tab button, it's customary to swipe either up or down to quickly navigate to an appropriate header to enter the new screen proper. However, none of the labels in the Scanner are accessible, making this impossible.

A possible solution is to make the overlay text on top a header… another good candidate is the label explaining that you can enter a barcode manually.

**Comment by teolemon** [comment]
I'm closing this one since you fixed it 🟢
