### ISSUE TITLE
[Bug] Manual barcode entry panel cuts off top of label

### ISSUE THREAD

**Issue by SpacyRicochet** [openfoodfacts/openfoodfacts-ios#938]
In iOS 15, the top of the label for the manual barcode entry in Scanner is cut off.

A likely reason is the view centering on the safe area, instead of aligning itself to the top of the safe area.

![IMG_1138](https://user-images.githubusercontent.com/904596/137535131-66e4a0a7-613a-421f-a34f-6b9e51e34c79.jpg)

**Comment by DilanAnuruddha** [comment]
@SpacyRicochet  Can I work on this?

**Comment by teolemon** [comment]
@DilanAnuruddha @SpacyRicochet has already made a PR on this one

**Comment by teolemon** [comment]
I'm closing this one since you fixed it 🟢
