### ISSUE TITLE
Continuous scan for barcodes & Overlay showing key data for products

### ISSUE THREAD

**Issue by snuff4** [openfoodfacts/openfoodfacts-ios#94]
**Checklist**
- [x] Bug Report - Reference issue #57 

**Summary:** 

`Motivation`

- As soon as a product is recognised, the User is taken to the full product view, interrupting the continuous flow of scanning products. 
- A need of a quick mode with key data of the product will be powerful, less intrusive and enhancing the User experience.
- In some cases if the barcode is not visible, the User should be able to type it.
- This will also resolve the issue continuous scan mode.
- The User will be reassured when the overlay parses data from database swiftly and works instantaneously when another barcode is recognised/not recognised. 

`Objective`

- The User should be able to continuously scan for barcodes.
- Option for typing the barcode manually, if failed to recognize.
- While the Overlay is on, it requires to recognize new barcodes that come into view.
- If the barcode is recognised and the product is present in the database, the User will be notified with a small overlay at the bottom, to display key information, when swiped up will display the full product page. The key data that will show, shall comprise of:
  - NutriScore color nutrition grade
  - Product Name
  - Quantity
  - Brand
- If the barcode is not recognized, the User can add the information about it:
  - Picture of the front, ingredients and nutrition facts.
  - Product Name
  - Quantity
  - Brand 
 
 
`Technical Details`

- A small custom overlay to type the barcode (after 5-10 seconds of failing to recognise) at the bottom will be present on the Barcode scan screen. 
- The entered barcode will be verified, and if it is not present, the screen will go to the Product Add ViewController storyboard.
- Implementation will require a reusable custom presentation using UIPresentationController. 
- As soon as the barcode is recognized, it will display the reusable custom presentation, which can be swiped down to continue scanning.
- Even when the product is recognized, and the overlay is displayed, the capture session should not stop running.
- Use the new lite API for retrieving the key data.

**Screenshots:** 

![screen shot 2018-05-13 at 2 21 14 pm](https://user-images.githubusercontent.com/30552772/39965552-0a227690-56b9-11e8-8629-671280e5f293.png)

**Comment by teolemon** [comment]
Fixed by @philippeauriach
