### ISSUE TITLE
[Issue] Strict SwiftLint check now breaks on a TODO

### ISSUE THREAD

**Issue by SpacyRicochet** [openfoodfacts/openfoodfacts-ios#942]
The strict SwiftLint check for each pull request now breaks on the TODO in the PersistenceManagerMock.

Considering that it's a mock, deleting the TODO should suffice, though disabling the TODO rule in tests is also an option. That would be the one I'd go for.

**Comment by teolemon** [comment]
I'm closing this one since you fixed it 🟢
