### ISSUE TITLE
Ask questions on uncomplete products

### ISSUE THREAD

**Issue by rudrankriyam** [openfoodfacts/openfoodfacts-ios#97]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker.](https://github.com/openfoodfacts/openfoodfacts-ios/issues)
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:** 

`Motivation  `

- There are some incomplete products on the website, which needs to be completed with verified facts.
- The best way to solve this issue is to ask the User itself.
- For instance the API could return a flag that nutrition information image is not clear, and the application could request the Users (in the form of showing them the original image) to take a better picture.

`Objective`

- Ask significant questions to User about the product they are looking at. 
- For example, the category of the product if it is unclear.
- The User should take a split second to answer.
- Information changed by the User will update the existing products and ensure quality.
 
`Technical Details`

- A custom action sheet will be created.
- Huge set of hard coded questions will be added after researching the products to get an idea.
- It will be based on [Open Food Facts - Drip Edit](https://photos.app.goo.gl/A7utryAtFY0jcytt2).
- Add new fields to the existing JSON API when a product information is requested.
- In the future, **Artificial Intelligence** shall be used to predict the questions required.
- The refreshed data will be sent to the backend team to update the existing product.
- A button Answer questions about this product so if the User might not be in the mood to answers questions, it will not interrupt the flow.

**Comment by teolemon** [comment]
We now have an API for this:
https://robotoff.openfoodfacts.org/api/v1/questions/8436551860381?lang=fr&count=3
https://github.com/openfoodfacts/robotoff/blob/master/doc/api.md
