### ISSUE TITLE
IDs instead of strings in XLIFF

### ISSUE THREAD

**Issue by yarons** [openfoodfacts/openfoodfacts-ios#98]
https://github.com/openfoodfacts/openfoodfacts-ios/blob/ca22005a0ce9692dfe7fa41537ea4c5d998ca5e3/Sources/ViewControllers/Products/Detail/Ingredients/IngredientsHeaderCellController.swift#L52
https://github.com/openfoodfacts/openfoodfacts-ios/blob/ca22005a0ce9692dfe7fa41537ea4c5d998ca5e3/Sources/ViewControllers/Products/Detail/NutritionTable/NutritionTableHeaderCellController.swift#L59
https://github.com/openfoodfacts/openfoodfacts-ios/blob/54a7a36c67c86c3f02812052a750d4cd66e3fb7a/Sources/ViewControllers/Products/Detail/Summary/SummaryHeaderCellController.swift#L50
https://github.com/openfoodfacts/openfoodfacts-ios/blob/35361e506235d5cd4dcc389fb3555c04b0d26857/Sources/ViewControllers/Common/TakePictureViewController.swift#L25
https://github.com/openfoodfacts/openfoodfacts-ios/blob/916063e5db54970046a2db6d5fba295e116f1e44/Sources/ViewControllers/User/LoginViewController.swift#L61
https://github.com/openfoodfacts/openfoodfacts-ios/blob/916063e5db54970046a2db6d5fba295e116f1e44/Sources/ViewControllers/User/LoginViewController.swift#L67

All these strings (and some others) have something in common: They all appear as IDs in translation instead of the actual string (Maybe removing the quotes will yield the required outcome).

This is what I see in the localization platform:

![image](https://user-images.githubusercontent.com/406826/40044224-6e7dfb10-582f-11e8-9ea5-53cf385a9ca9.png)

**Comment by snuff4** [comment]
As you can see, these are test cases, in the OpenFoodFactsTests/Localizable.strings.
I have offered a solution in PR #90 
Can you go through it?

**Comment by yarons** [comment]
I just looked at it, as said, it could lead to repetition so what I suggest is filtering out the test for XLIFF generation, I need to go through this and see if I can find a proper solution.

**Comment by aleene** [comment]
The xliff's are no longer used for translations. This is no longer relevant.
