### ISSUE TITLE
Duplicate string instead of trying to concatenate

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#99]
Duplicate string instead of trying to concatenate. Some languages don't work like English. That's more work for translators, but that's the proper way.

"Take a picture of the product's" + X

>> 'Take a picture of the product's ingredients'
>> 'Take a picture of the product's nutrition table'
>> 'Take a picture of the product's front'

**Comment by philippeauriach** [comment]
Fixed in #156

**Comment by teolemon** [comment]
Thanks @philippeauriach 
closing
